-- Auto-generated by gasfile on: 01-Mar-2010 22:21:20
model = 'composite gas'
equation_of_state = 'perfect gas'
thermal_behaviour = 'thermally perfect'
mixing_rule = 'Wilke'
sound_speed = 'equilibrium'
diffusion_coefficients = 'hard sphere'
ignore_mole_fraction = 1.0e-15
T_COLD = 20.0
species = {'O2', 'N2', 'H2', 'O', 'H', 'H2O', 'OH', 'HO2', }

O2 = {}
O2.M = {
  value = 0.031999,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O2.d = {
  value = 3.433e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
O2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 139,
    mu_ref = 1.919e-05,
  },
  model = "Sutherland",
}
O2.thermal_conductivity = {
  parameters = {
    S = 240,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0244,
    T_ref = 273,
  },
  model = "Sutherland",
}
O2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -34255.6342,
      484.700097,
      1.119010961,
      0.00429388924,
      -6.83630052e-07,
      -2.0233727e-09,
      1.039040018e-12,
      -3391.45487,
      18.4969947,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1037939.022,
      2344.830282,
      1.819732036,
      0.001267847582,
      -2.188067988e-07,
      2.053719572e-11,
      -8.19346705e-16,
      -16890.10929,
      17.38716506,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      497529430,
      -286610.6874,
      66.9035225,
      -0.00616995902,
      3.016396027e-07,
      -7.4214166e-12,
      7.27817577e-17,
      2293554.027,
      -553.062161,
    },
  },
  ref = "from CEA2::thermo.inp",
}
N2 = {}
N2.M = {
  value = 0.028013,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
N2.d = {
  value = 3.667e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
N2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 107,
    mu_ref = 1.663e-05,
  },
  model = "Sutherland",
}
N2.thermal_conductivity = {
  parameters = {
    S = 150,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0242,
    T_ref = 273,
  },
  model = "Sutherland",
}
N2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      22103.71497,
      -381.846182,
      6.08273836,
      -0.00853091441,
      1.384646189e-05,
      -9.62579362e-09,
      2.519705809e-12,
      710.846086,
      -10.76003744,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      587712.406,
      -2239.249073,
      6.06694922,
      -0.00061396855,
      1.491806679e-07,
      -1.923105485e-11,
      1.061954386e-15,
      12832.10415,
      -15.86640027,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      831013916,
      -642073.354,
      202.0264635,
      -0.03065092046,
      2.486903333e-06,
      -9.70595411e-11,
      1.437538881e-15,
      4938707.04,
      -1672.09974,
    },
  },
  ref = "from CEA2::thermo.inp",
}
H2 = {}
H2.M = {
  value = 0.00201588,
  reference = "molecular weight from CEA2",
  description = "molecular mass",
  units = "kg/mol",
}
H2.d = {
  value = 3.433e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
H2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 139,
    mu_ref = 1.919e-05,
  },
  model = "Sutherland",
}
H2.thermal_conductivity = {
  parameters = {
    S = 240,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0244,
    T_ref = 273,
  },
  model = "Sutherland",
}
H2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      40783.2321,
      -800.918604,
      8.21470201,
      -0.01269714457,
      1.753605076e-05,
      -1.20286027e-08,
      3.36809349e-12,
      2682.484665,
      -30.43788844,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      560812.801,
      -837.150474,
      2.975364532,
      0.001252249124,
      -3.74071619e-07,
      5.9366252e-11,
      -3.6069941e-15,
      5339.82441,
      -2.202774769,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      496688412,
      -314754.7149,
      79.8412188,
      -0.00841478921,
      4.75324835e-07,
      -1.371873492e-11,
      1.605461756e-16,
      2488433.516,
      -669.572811,
    },
  },
  ref = "from CEA2::thermo.inp",
}
O = {}
O.M = {
  value = 0.0159994,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
O.viscosity = {
  parameters = {
    {
      A = 0.77269241,
      C = -58502.098,
      B = 83.842977,
      T_high = 5000,
      T_low = 1000,
      D = 0.85100827,
    },
    {
      A = 0.87669586,
      C = -1088456.6,
      B = 1015.842,
      T_high = 15000,
      T_low = 5000,
      D = -0.18001077,
    },
    ref = "from CEA2::trans.inp which cites Levin et al (1990)",
  },
  model = "CEA",
}
O.thermal_conductivity = {
  parameters = {
    {
      A = 0.77271664,
      C = -58580.966,
      B = 83.9891,
      T_high = 5000,
      T_low = 1000,
      D = 1.51799,
    },
    {
      A = 0.87676666,
      C = -1090669,
      B = 1017.0744,
      T_high = 15000,
      T_low = 5000,
      D = 0.48644232,
    },
    ref = "from CEA2::trans.inp which cites Levin et al (1990)",
  },
  model = "CEA",
}
O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -7953.6113,
      160.7177787,
      1.966226438,
      0.00101367031,
      -1.110415423e-06,
      6.5175075e-10,
      -1.584779251e-13,
      28403.62437,
      8.40424182,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      261902.0262,
      -729.872203,
      3.31717727,
      -0.000428133436,
      1.036104594e-07,
      -9.43830433e-12,
      2.725038297e-16,
      33924.2806,
      -0.667958535,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      177900426.4,
      -108232.8257,
      28.10778365,
      -0.002975232262,
      1.854997534e-07,
      -5.79623154e-12,
      7.191720164e-17,
      889094.263,
      -218.1728151,
    },
  },
  ref = "from CEA2::thermo.inp",
}
H = {}
H.M = {
  value = 0.00100794,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
H.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
H.viscosity = {
  parameters = {
    {
      A = 0.74226149,
      C = 185541.65,
      B = -401.32865,
      T_high = 5000,
      T_low = 1000,
      D = 0.046741844,
    },
    {
      A = 0.87486623,
      C = 7095504.8,
      B = -2502.2902,
      T_high = 15000,
      T_low = 5000,
      D = -0.93888455,
    },
    ref = "from CEA2::trans.inp which cites Vanderslice et al. (1962)",
  },
  model = "CEA",
}
H.thermal_conductivity = {
  parameters = {
    {
      A = 0.74166119,
      C = 187756.42,
      B = -404.87203,
      T_high = 5000,
      T_low = 1000,
      D = 3.4843121,
    },
    {
      A = 0.87447639,
      C = 7108129.4,
      B = -2508.9452,
      T_high = 15000,
      T_low = 5000,
      D = 2.4970991,
    },
    ref = "from CEA2::trans.inp which cites Vanderslice et al. (1962)",
  },
  model = "CEA",
}
H.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      25473.708,
      -0.446682853,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      60.7877425,
      -0.181935442,
      2.50021182,
      -1.22651286e-07,
      3.73287633e-11,
      -5.68774456e-15,
      3.4102102e-19,
      25474.864,
      -0.448191777,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      217375769,
      -131203.54,
      33.991742,
      -0.00381399968,
      2.43285484e-07,
      -7.69427554e-12,
      9.64410563e-17,
      1067638.09,
      -274.230105,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
H2O = {}
H2O.M = {
  value = 0.01801528,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
H2O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
H2O.viscosity = {
  parameters = {
    {
      A = 0.50019557,
      C = 88163.892,
      B = -697.12796,
      T_high = 1073.2,
      T_low = 373.2,
      D = 3.0836508,
    },
    {
      A = 0.58988538,
      C = 54263.513,
      B = -537.69814,
      T_high = 5000,
      T_low = 1073.2,
      D = 2.3386375,
    },
    {
      A = 0.64330087,
      C = -377422.83,
      B = -95.668913,
      T_high = 15000,
      T_low = 5000,
      D = 1.812519,
    },
    ref = "from CEA2::trans.inp which cites Sengers and Watson (1986)",
  },
  model = "CEA",
}
H2O.thermal_conductivity = {
  parameters = {
    {
      A = 1.0966389,
      C = 106234.08,
      B = -555.13429,
      T_high = 1073.2,
      T_low = 373.2,
      D = -0.2466455,
    },
    {
      A = 0.39367933,
      C = 612174.58,
      B = -2252.4226,
      T_high = 5000,
      T_low = 1073.2,
      D = 5.8011317,
    },
    {
      A = -0.41858737,
      C = 19179190,
      B = -14096.649,
      T_high = 15000,
      T_low = 5000,
      D = 14.345613,
    },
    ref = "from CEA2::trans.inp which cites Sengers and Watson (1986)",
  },
  model = "CEA",
}
H2O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -39479.6083,
      575.573102,
      0.931782653,
      0.00722271286,
      -7.34255737e-06,
      4.95504349e-09,
      -1.336933246e-12,
      -33039.7431,
      17.24205775,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      1034972.096,
      -2412.698562,
      4.64611078,
      0.002291998307,
      -6.83683048e-07,
      9.42646893e-11,
      -4.82238053e-15,
      -13842.86509,
      -7.97814851,
    },
  },
  ref = "from CEA2::thermo.inp",
}
OH = {}
OH.M = {
  value = 0.01700734,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
OH.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
OH.viscosity = {
  parameters = {
    {
      A = 0.59711536,
      C = 37606.286,
      B = -461.00678,
      T_high = 5000,
      T_low = 1000,
      D = 2.4041761,
    },
    {
      A = 0.64287721,
      C = -88543.767,
      B = -181.73747,
      T_high = 15000,
      T_low = 5000,
      D = 1.9636057,
    },
    ref = "from CEA2::trans.inp which cites Svehla (1994)",
  },
  model = "CEA",
}
OH.thermal_conductivity = {
  parameters = {
    {
      A = 0.68627561,
      C = 27559.033,
      B = -740.33274,
      T_high = 5000,
      T_low = 1000,
      D = 2.8308741,
    },
    {
      A = -0.47918112,
      C = 7050995.2,
      B = -9376.9908,
      T_high = 15000,
      T_low = 5000,
      D = 14.203688,
    },
    ref = "from CEA2::trans.inp which cites Svehla (1994)",
  },
  model = "CEA",
}
OH.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -1998.85899,
      93.0013616,
      3.050854229,
      0.001529529288,
      -3.157890998e-06,
      3.31544618e-09,
      -1.138762683e-12,
      2991.214235,
      4.67411079,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      1017393.379,
      -2509.957276,
      5.11654786,
      0.000130529993,
      -8.28432226e-08,
      2.006475941e-11,
      -1.556993656e-15,
      20196.40206,
      -11.01282337,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      284723419.3,
      -185953.2612,
      50.082409,
      -0.00514237498,
      2.875536589e-07,
      -8.22881796e-12,
      9.56722902e-17,
      1468393.908,
      -402.355558,
    },
  },
  ref = "from CEA2::thermo.inp",
}
HO2 = {}
HO2.M = {
  value = 0.03300674,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
HO2.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
HO2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
HO2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
HO2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -75988.8254,
      1329.383918,
      -4.67738824,
      0.02508308202,
      -3.006551588e-05,
      1.895600056e-08,
      -4.82856739e-12,
      -5873.35096,
      51.9360214,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1810669.724,
      4963.19203,
      -1.039498992,
      0.00456014853,
      -1.061859447e-06,
      1.144567878e-10,
      -4.76306416e-15,
      -32008.1719,
      40.6685092,
    },
  },
  ref = "from CEA2::thermo.inp",
}
