-- Auto-generated by gasfile on: 11-Mar-2013 20:27:58
model = 'composite gas'
equation_of_state = 'perfect gas'
thermal_behaviour = 'thermal nonequilibrium'
mixing_rule = 'GuptaYos'
sound_speed = 'equilibrium'
diffusion_coefficients = 'GuptaYos'
min_massf = 1.000000e-15

thermal_modes = { 'transrotational', 'vibroelectronic' }

transrotational = {}
transrotational.type = 'constant Cv'
transrotational.iT = 0
transrotational.components = { 'all-translation', 'all-rotation' }

vibroelectronic = {}
vibroelectronic.type = 'variable Cv'
vibroelectronic.iT = 1
vibroelectronic.components = { 'all-vibration', 'O2-electronic'}
vibroelectronic.T_min = 20.000000
vibroelectronic.T_max = 100000.000000
vibroelectronic.iterative_method = 'NewtonRaphson'
vibroelectronic.convergence_tolerance = 1.000000e-06
vibroelectronic.max_iterations = 100

species = {'O2', 'O', }

O2 = {}
O2.species_type = "nonpolar diatomic"
O2.oscillator_type = "truncated harmonic"
O2.M = {
  value = 32.00e-3,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O2.theta_v = {
  value = 2240.0
}
O2.s_0 = {
  value = 6411.18,
  reference = "NIST Chemistry WebBook: http://webbook.nist.gov/chemistry/",
  description = "Standard state entropy at 1 bar",
  units = "J/kg-K",
}
O2.h_f = {
  value = 0,
  reference = "from CEA2::thermo.inp",
  description = "Heat of formation",
  units = "J/kg",
}
O2.I = {
  value = 36397495,
  reference = "NIST Chemistry WebBook: http://webbook.nist.gov/chemistry/",
  description = "Ground state ionization energy",
  units = "J/kg",
}
O2.Z = {
  value = 0,
  reference = "NA",
  description = "Charge number",
  units = "ND",
}
O2.eps0 = {
  value = 1.473162086e-21,
  reference = "Svehla (1962) NASA Technical Report R-132",
  description = "Depth of the intermolecular potential minimum",
  units = "J",
}
O2.sigma = {
  value = 3.467e-10,
  reference = "Svehla (1962) NASA Technical Report R-132",
  description = "Hard sphere collision diameter",
  units = "m",
}
O2.charge = 0
O2.r0 = {
  value = 3.541e-10,
  reference = "Hirschfelder, Curtiss, and Bird (1954). Molecular theory of gases and liquids.",
  description = "Zero of the intermolecular potential",
  units = "m",
}
O2.r_eq = {
  value = 1.21e-10,
  reference = "See ilev_0 data below",
  description = "Equilibrium intermolecular distance",
  units = "m",
}
O2.f_m = {
  value = 1,
  reference = "Thivet et al (1991) Phys. Fluids A 3 (11)",
  description = "Mass factor = ( M ( Ma^2 + Mb^2 ) / ( 2 Ma Mb ( Ma + Mb ) )",
  units = "ND",
}
O2.mu = {
  value = 2.65676e-26,
  reference = "See molecular weight for O",
  description = "Reduced mass of constituent atoms",
  units = "kg/particle",
}
O2.alpha = {
  value = 0.793,
  reference = "FIXME: Rowans mTg_input.dat",
  description = "Polarizability",
  units = "ND",
}
O2.mu_B = {
  value = 8.199176e-19,
  reference = "FIXME: Rowans mTg_input.dat",
  description = "Dipole moment",
  units = "Debye",
}
O2.electronic_levels = {
  n_levels = 1,
  ref = "Spradian07::diatom.dat",
  ilev_0 = {
    0,
    1.2075,
    3,
    41280,
    1580.193,
    11.9808,
    0.04747,
    -0.001273,
    1.44563,
    0.01593,
    4.839e-06,
    0,
    0,
    0,
    3,
  },
  ilev_1 = {
    7918.04,
    1.2156,
    2,
    33410,
    1509.763,
    13.065,
    0.011,
    0,
    1.42642,
    0.0172,
    4.86e-06,
    0,
    0,
    2,
    1,
  },
  ilev_2 = {
    13195.1,
    1.2269,
    1,
    28160,
    1432.77,
    14,
    0,
    0,
    1.40037,
    0.0182,
    5.351e-06,
    3.2e-08,
    0,
    0,
    1,
  },
  ilev_3 = {
    33057.3,
    1.5174,
    1,
    8620,
    794.29,
    12.736,
    -0.2444,
    0,
    0.9155,
    0.01391,
    7.4e-06,
    0,
    0,
    0,
    1,
  },
  ilev_4 = {
    34690,
    1.48,
    6,
    6960,
    850,
    20,
    0,
    0,
    0.96,
    0.0262,
    0,
    0,
    145.9,
    2,
    3,
  },
}
O2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -34255.6342,
      484.700097,
      1.119010961,
      0.00429388924,
      -6.83630052e-07,
      -2.0233727e-09,
      1.039040018e-12,
      -3391.45487,
      18.4969947,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1037939.022,
      2344.830282,
      1.819732036,
      0.001267847582,
      -2.188067988e-07,
      2.053719572e-11,
      -8.19346705e-16,
      -16890.10929,
      17.38716506,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      497529430,
      -286610.6874,
      66.9035225,
      -0.00616995902,
      3.016396027e-07,
      -7.4214166e-12,
      7.27817577e-17,
      2293554.027,
      -553.062161,
    },
  },
  ref = "from CEA2::thermo.inp",
}
O2.viscosity = {
  model = 'collision integrals'
}
O2.thermal_conductivity = {
  model = 'collision integrals'
}

O = {}
O.species_type = "monatomic"
O.M = {
  value = 16.00e-3,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O.s_0 = {
  value = 10066.56,
  reference = "NIST Chemistry WebBook: http://webbook.nist.gov/chemistry/",
  description = "Standard state entropy at 1 bar",
  units = "J/kg-K",
}
O.h_f = {
  value = 1.5424e7,
  reference = "from CEA2::thermo.inp",
  description = "Heat of formation",
  units = "J/kg",
}
O.I = {
  value = 82124270,
  reference = "NIST Chemistry WebBook: http://webbook.nist.gov/chemistry/",
  description = "Ground state ionization energy",
  units = "J/kg",
}
O.Z = {
  value = 0,
  reference = "NA",
  description = "Charge number",
  units = "ND",
}
O.eps0 = {
  value = 1.473162086e-21,
  reference = "Svehla (1962) NASA Technical Report R-132",
  description = "Depth of the intermolecular potential minimum",
  units = "J",
}
O.sigma = {
  value = 3.05e-10,
  reference = "Svehla (1962) NASA Technical Report R-132",
  description = "Hard sphere collision diameter",
  units = "m",
}
O.charge = 0
O.electronic_levels = {
  n_levels = 1,
  ref = "NIST ASD: http://physics.nist.gov/PhysRefData/ASD/index.html",
  ilev_0 = {
    2,
    77.97,
    9,
    -1,
    1,
    1,
    2,
  },
  ilev_1 = {
    2,
    15867.86,
    5,
    -1,
    2,
    0,
    2,
  },
  ilev_2 = {
    2,
    33792.58,
    1,
    -1,
    0,
    0,
    2,
  },
  ilev_3 = {
    2,
    73768.2,
    5,
    0,
    0,
    2,
    1,
  },
  ilev_4 = {
    2,
    76794.98,
    3,
    0,
    0,
    1,
    1,
  },
}
O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -7953.6113,
      160.7177787,
      1.966226438,
      0.00101367031,
      -1.110415423e-06,
      6.5175075e-10,
      -1.584779251e-13,
      28403.62437,
      8.40424182,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      261902.0262,
      -729.872203,
      3.31717727,
      -0.000428133436,
      1.036104594e-07,
      -9.43830433e-12,
      2.725038297e-16,
      33924.2806,
      -0.667958535,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      177900426.4,
      -108232.8257,
      28.10778365,
      -0.002975232262,
      1.854997534e-07,
      -5.79623154e-12,
      7.191720164e-17,
      889094.263,
      -218.1728151,
    },
  },
  ref = "from CEA2::thermo.inp",
}
O.viscosity = {
  model = 'collision integrals'
}
O.thermal_conductivity = {
  model = 'collision integrals'
}

collision_integrals = {
  {
    i = "O2",
    j = "O2",
    reference = "Wright et al, AIAA Journal Vol. 43 No. 12 December 2005",
    model = "GuptaYos curve fits",
    parameters = {
      {
        Pi_Omega_11 = {
          -0.0023,
          0.0516,
          -0.5785,
          5.6041,
        },
        T_high = 15000,
        T_low = 300,
        D = {
          0.0023,
          -0.0516,
          2.0785,
          -8.6796,
        },
        Pi_Omega_22 = {
          -0.0089,
          0.2066,
          -1.7522,
          8.6099,
        },
      },
    },
  },
  {
    i = "O2",
    j = "O",
    reference = "Wright et al, AIAA Journal Vol. 43 No. 12 December 2005",
    model = "GuptaYos curve fits",
    parameters = {
      {
        Pi_Omega_11 = {
          -0.0055,
          0.1174,
          -1.077,
          6.6923,
        },
        T_high = 10000,
        T_low = 300,
        D = {
          0.0055,
          -0.1174,
          2.577,
          -9.5651,
        },
        Pi_Omega_22 = {
          -0.0049,
          0.102,
          -0.9228,
          6.3111,
        },
      },
    },
  },
  {
    i = "O",
    j = "O",
    reference = "Wright et al, AIAA Journal Vol. 43 No. 12 December 2005",
    model = "GuptaYos curve fits",
    parameters = {
      {
        Pi_Omega_11 = {
          -0.0055,
          0.1245,
          -1.2233,
          7.2312,
        },
        T_high = 20000,
        T_low = 300,
        D = {
          0.0055,
          -0.1245,
          2.7233,
          -9.9601,
        },
        Pi_Omega_22 = {
          -0.0032,
          0.0717,
          -0.8058,
          6.2443,
        },
      },
    },
  },

}
