-- this file has been automatically generated by chemkin2libgas.py
-- scaling factor, 1/R
S = 1.0/1.987

reaction{'O + H + M <=> OH + M',
   fr={'Arrhenius', A=5.00000e+17, n=-1.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r0'
}
reaction{'O + H2 <=> H + OH',
   fr={'Arrhenius', A=5.00000e+04, n=2.67000e+00, T_a=6.29000e+03*S},
   label='r1'
}
reaction{'O + HO2 <=> OH + O2',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r2'
}
reaction{'O + CH2 <=> H + CHO',
   fr={'Arrhenius', A=8.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r3'
}
reaction{'O + CH2_S <=> H + CHO',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r4'
}
reaction{'O + CH3 <=> H + CH2O',
   fr={'Arrhenius', A=8.43000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r5'
}
reaction{'O + CH4 <=> OH + CH3',
   fr={'Arrhenius', A=1.02000e+09, n=1.50000e+00, T_a=8.60000e+03*S},
   label='r6'
}
reaction{'O + CO + M <=> CO2 + M',
   fr={'Arrhenius', A=6.02000e+14, n=0.00000e+00, T_a=3.00000e+03*S},
   efficiencies={H2=2.00, O2=6.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=3.50, C2H6=3.00, Ar=0.50},
   label='r7'
}
reaction{'O + CHO <=> OH + CO',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r8'
}
reaction{'O + CHO <=> H + CO2',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r9'
}
reaction{'O + CH2O <=> OH + CHO',
   fr={'Arrhenius', A=3.90000e+13, n=0.00000e+00, T_a=3.54000e+03*S},
   label='r10'
}
reaction{'O + C2H2 <=> CH2_S + CO',
   fr={'Arrhenius', A=1.02000e+07, n=2.00000e+00, T_a=1.90000e+03*S},
   label='r11'
}
reaction{'O + C2H2 <=> CO + CH2',
   fr={'Arrhenius', A=1.02000e+07, n=2.00000e+00, T_a=1.90000e+03*S},
   label='r12'
}
reaction{'O + C2H4 <=> CH3 + CHO',
   fr={'Arrhenius', A=1.92000e+07, n=1.83000e+00, T_a=2.20000e+02*S},
   label='r13'
}
reaction{'O + C2H5 <=> CH3 + CH2O',
   fr={'Arrhenius', A=1.32000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r14'
}
reaction{'O + C2H6 <=> OH + C2H5',
   fr={'Arrhenius', A=8.98000e+07, n=1.92000e+00, T_a=5.69000e+03*S},
   label='r15'
}
reaction{'O2 + CO <=> O + CO2',
   fr={'Arrhenius', A=2.50000e+12, n=0.00000e+00, T_a=4.78000e+04*S},
   label='r16'
}
reaction{'O2 + CH2O <=> HO2 + CHO',
   fr={'Arrhenius', A=1.00000e+14, n=0.00000e+00, T_a=4.00000e+04*S},
   label='r17'
}
reaction{'H + O2 + M <=> HO2 + M',
   fr={'Arrhenius', A=2.80000e+18, n=-8.60000e-01, T_a=0.00000e+00*S},
   efficiencies={O2=0.00, H2O=0.00, CO=0.75, CO2=1.50, C2H6=1.50, N2=0.00, Ar=0.00},
   label='r18'
}
reaction{'H + 2O2 <=> HO2 + O2',
   fr={'Arrhenius', A=3.00000e+20, n=-1.72000e+00, T_a=0.00000e+00*S},
   label='r19'
}
reaction{'H + O2 + H2O <=> HO2 + H2O',
   fr={'Arrhenius', A=9.38000e+18, n=-7.60000e-01, T_a=0.00000e+00*S},
   label='r20'
}
reaction{'H + O2 + N2 <=> HO2 + N2',
   fr={'Arrhenius', A=3.75000e+20, n=-1.72000e+00, T_a=0.00000e+00*S},
   label='r21'
}
reaction{'H + O2 + Ar <=> HO2 + Ar',
   fr={'Arrhenius', A=7.00000e+17, n=-8.00000e-01, T_a=0.00000e+00*S},
   label='r22'
}
reaction{'H + O2 <=> O + OH',
   fr={'Arrhenius', A=8.30000e+13, n=0.00000e+00, T_a=1.44130e+04*S},
   label='r23'
}
reaction{'2H + M <=> H2 + M',
   fr={'Arrhenius', A=1.00000e+18, n=-1.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=0.00, H2O=0.00, CH4=2.00, CO2=0.00, C2H6=3.00, Ar=0.63},
   label='r24'
}
reaction{'2H + H2 <=> 2H2',
   fr={'Arrhenius', A=9.00000e+16, n=-6.00000e-01, T_a=0.00000e+00*S},
   label='r25'
}
reaction{'2H + H2O <=> H2 + H2O',
   fr={'Arrhenius', A=6.00000e+19, n=-1.25000e+00, T_a=0.00000e+00*S},
   label='r26'
}
reaction{'2H + CO2 <=> H2 + CO2',
   fr={'Arrhenius', A=5.50000e+20, n=-2.00000e+00, T_a=0.00000e+00*S},
   label='r27'
}
reaction{'H + OH + M <=> H2O + M',
   fr={'Arrhenius', A=2.20000e+22, n=-2.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=0.73, H2O=3.65, CH4=2.00, C2H6=3.00, Ar=0.38},
   label='r28'
}
reaction{'H + HO2 <=> O2 + H2',
   fr={'Arrhenius', A=2.80000e+13, n=0.00000e+00, T_a=1.06800e+03*S},
   label='r29'
}
reaction{'H + HO2 <=> 2OH',
   fr={'Arrhenius', A=1.34000e+14, n=0.00000e+00, T_a=6.35000e+02*S},
   label='r30'
}
reaction{'H + H2O2 <=> HO2 + H2',
   fr={'Arrhenius', A=1.21000e+07, n=2.00000e+00, T_a=5.20000e+03*S},
   label='r31'
}
reaction{'H + CH2 ( + M ) <=> CH3 ( + M )',
   fr={'pressure dependent',
       k_inf={A=2.50000e+16, n=-8.00000e-01, T_a=0.00000e+00*S},
       k_0={A=3.20000e+27, n=-3.14000e+00, T_a=1.23000e+03*S},
       Troe={a=0.6800, T3=78.00, T1=1995.00, T2=5590.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r32'
}
reaction{'H + CH3 ( + M ) <=> CH4 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.27000e+16, n=-6.30000e-01, T_a=3.83000e+02*S},
       k_0={A=2.47700e+33, n=-4.76000e+00, T_a=2.44000e+03*S},
       Troe={a=0.7830, T3=74.00, T1=2941.00, T2=6964.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r33'
}
reaction{'H + CH4 <=> CH3 + H2',
   fr={'Arrhenius', A=6.60000e+08, n=1.62000e+00, T_a=1.08400e+04*S},
   label='r34'
}
reaction{'H + CHO ( + M ) <=> CH2O ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.09000e+12, n=4.80000e-01, T_a=-2.60000e+02*S},
       k_0={A=1.35000e+24, n=-2.57000e+00, T_a=1.42500e+03*S},
       Troe={a=0.7824, T3=271.00, T1=2755.00, T2=6570.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r35'
}
reaction{'H + CHO <=> H2 + CO',
   fr={'Arrhenius', A=7.34000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r36'
}
reaction{'H + CH2O ( + M ) <=> CH3O ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.40000e+11, n=4.54000e-01, T_a=2.60000e+03*S},
       k_0={A=2.20000e+30, n=-4.80000e+00, T_a=5.56000e+03*S},
       Troe={a=0.7580, T3=94.00, T1=1555.00, T2=4200.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r37'
}
reaction{'H + CH2O <=> CHO + H2',
   fr={'Arrhenius', A=2.30000e+10, n=1.05000e+00, T_a=3.27500e+03*S},
   label='r38'
}
reaction{'H + CH3O <=> OH + CH3',
   fr={'Arrhenius', A=3.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r39'
}
reaction{'H + C2H2 ( + M ) <=> C2H3 ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.60000e+12, n=0.00000e+00, T_a=2.40000e+03*S},
       k_0={A=3.80000e+40, n=-7.27000e+00, T_a=7.22000e+03*S},
       Troe={a=0.7507, T3=98.50, T1=1302.00, T2=4167.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r40'
}
reaction{'H + C2H3 ( + M ) <=> C2H4 ( + M )',
   fr={'pressure dependent',
       k_inf={A=6.08000e+12, n=2.70000e-01, T_a=2.80000e+02*S},
       k_0={A=1.40000e+30, n=-3.86000e+00, T_a=3.32000e+03*S},
       Troe={a=0.7820, T3=207.50, T1=2663.00, T2=6095.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r41'
}
reaction{'H + C2H3 <=> H2 + C2H2',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r42'
}
reaction{'H + C2H4 ( + M ) <=> C2H5 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.08000e+12, n=4.54000e-01, T_a=1.82000e+03*S},
       k_0={A=1.20000e+42, n=-7.62000e+00, T_a=6.97000e+03*S},
       Troe={a=0.9753, T3=210.00, T1=984.00, T2=4374.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r43'
}
reaction{'H + C2H4 <=> C2H3 + H2',
   fr={'Arrhenius', A=1.32500e+06, n=2.53000e+00, T_a=1.22400e+04*S},
   label='r44'
}
reaction{'H + C2H5 ( + M ) <=> C2H6 ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.21000e+17, n=-9.90000e-01, T_a=1.58000e+03*S},
       k_0={A=1.99000e+41, n=-7.08000e+00, T_a=6.68500e+03*S},
       Troe={a=0.8422, T3=125.00, T1=2219.00, T2=6882.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r45'
}
reaction{'H + C2H6 <=> C2H5 + H2',
   fr={'Arrhenius', A=1.15000e+08, n=1.90000e+00, T_a=7.53000e+03*S},
   label='r46'
}
reaction{'H2 + CO ( + M ) <=> CH2O ( + M )',
   fr={'pressure dependent',
       k_inf={A=4.30000e+07, n=1.50000e+00, T_a=7.96000e+04*S},
       k_0={A=5.07000e+27, n=-3.42000e+00, T_a=8.43500e+04*S},
       Troe={a=0.9320, T3=197.00, T1=1540.00, T2=10300.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r47'
}
reaction{'OH + H2 <=> H + H2O',
   fr={'Arrhenius', A=2.16000e+08, n=1.51000e+00, T_a=3.43000e+03*S},
   label='r48'
}
reaction{'2OH ( + M ) <=> H2O2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=7.40000e+13, n=-3.70000e-01, T_a=0.00000e+00*S},
       k_0={A=2.30000e+18, n=-9.00000e-01, T_a=-1.70000e+03*S},
       Troe={a=0.7346, T3=94.00, T1=1756.00, T2=5182.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r49'
}
reaction{'2OH <=> O + H2O',
   fr={'Arrhenius', A=3.57000e+04, n=2.40000e+00, T_a=-2.11000e+03*S},
   label='r50'
}
reaction{'OH + HO2 <=> O2 + H2O',
   fr={'Arrhenius', A=2.90000e+13, n=0.00000e+00, T_a=-5.00000e+02*S},
   label='r51'
}
reaction{'OH + H2O2 <=> HO2 + H2O',
   fr={'Arrhenius', A=5.80000e+14, n=0.00000e+00, T_a=9.56000e+03*S},
   label='r52'
}
reaction{'OH + CH2 <=> H + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r53'
}
reaction{'OH + CH2_S <=> H + CH2O',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r54'
}
reaction{'OH + CH3 <=> CH2 + H2O',
   fr={'Arrhenius', A=5.60000e+07, n=1.60000e+00, T_a=5.42000e+03*S},
   label='r55'
}
reaction{'OH + CH3 <=> CH2_S + H2O',
   fr={'Arrhenius', A=2.50100e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r56'
}
reaction{'OH + CH4 <=> CH3 + H2O',
   fr={'Arrhenius', A=1.00000e+08, n=1.60000e+00, T_a=3.12000e+03*S},
   label='r57'
}
reaction{'OH + CO <=> H + CO2',
   fr={'Arrhenius', A=4.76000e+07, n=1.22800e+00, T_a=7.00000e+01*S},
   label='r58'
}
reaction{'OH + CHO <=> H2O + CO',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r59'
}
reaction{'OH + CH2O <=> CHO + H2O',
   fr={'Arrhenius', A=3.43000e+09, n=1.18000e+00, T_a=-4.47000e+02*S},
   label='r60'
}
reaction{'OH + C2H2 <=> CH3 + CO',
   fr={'Arrhenius', A=4.83000e-04, n=4.00000e+00, T_a=-2.00000e+03*S},
   label='r61'
}
reaction{'OH + C2H3 <=> H2O + C2H2',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r62'
}
reaction{'OH + C2H4 <=> C2H3 + H2O',
   fr={'Arrhenius', A=3.60000e+06, n=2.00000e+00, T_a=2.50000e+03*S},
   label='r63'
}
reaction{'OH + C2H6 <=> C2H5 + H2O',
   fr={'Arrhenius', A=3.54000e+06, n=2.12000e+00, T_a=8.70000e+02*S},
   label='r64'
}
reaction{'2HO2 <=> O2 + H2O2',
   fr={'Arrhenius', A=1.30000e+11, n=0.00000e+00, T_a=-1.63000e+03*S},
   label='r65'
}
-- duplicate reaction found, including...
reaction{'2HO2 <=> O2 + H2O2',
   fr={'Arrhenius', A=4.20000e+14, n=0.00000e+00, T_a=1.20000e+04*S},
   label='r66'
}
-- duplicate reaction found, including...
reaction{'HO2 + CH2 <=> OH + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r67'
}
reaction{'HO2 + CH3 <=> O2 + CH4',
   fr={'Arrhenius', A=1.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r68'
}
reaction{'HO2 + CH3 <=> OH + CH3O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r69'
}
reaction{'HO2 + CO <=> OH + CO2',
   fr={'Arrhenius', A=1.50000e+14, n=0.00000e+00, T_a=2.36000e+04*S},
   label='r70'
}
reaction{'HO2 + CH2O <=> CHO + H2O2',
   fr={'Arrhenius', A=1.00000e+12, n=0.00000e+00, T_a=8.00000e+03*S},
   label='r71'
}
reaction{'CH2 + O2 <=> OH + CHO',
   fr={'Arrhenius', A=1.32000e+13, n=0.00000e+00, T_a=1.50000e+03*S},
   label='r72'
}
reaction{'CH2 + H2 <=> H + CH3',
   fr={'Arrhenius', A=5.00000e+05, n=2.00000e+00, T_a=7.23000e+03*S},
   label='r73'
}
reaction{'2CH2 <=> H2 + C2H2',
   fr={'Arrhenius', A=3.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r74'
}
reaction{'CH2 + CH3 <=> H + C2H4',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r75'
}
reaction{'CH2 + CH4 <=> 2CH3',
   fr={'Arrhenius', A=2.46000e+06, n=2.00000e+00, T_a=8.27000e+03*S},
   label='r76'
}
reaction{'CH2_S + N2 <=> CH2 + N2',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=6.00000e+02*S},
   label='r77'
}
reaction{'CH2_S + Ar <=> CH2 + Ar',
   fr={'Arrhenius', A=9.00000e+12, n=0.00000e+00, T_a=6.00000e+02*S},
   label='r78'
}
reaction{'CH2_S + O2 <=> H + OH + CO',
   fr={'Arrhenius', A=2.80000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r79'
}
reaction{'CH2_S + O2 <=> CO + H2O',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r80'
}
reaction{'CH2_S + H2 <=> CH3 + H',
   fr={'Arrhenius', A=7.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r81'
}
reaction{'CH2_S + H2O <=> CH2 + H2O',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r82'
}
reaction{'CH2_S + CH3 <=> H + C2H4',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=-5.70000e+02*S},
   label='r83'
}
reaction{'CH2_S + CH4 <=> 2CH3',
   fr={'Arrhenius', A=1.60000e+13, n=0.00000e+00, T_a=-5.70000e+02*S},
   label='r84'
}
reaction{'CH2_S + CO <=> CH2 + CO',
   fr={'Arrhenius', A=9.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r85'
}
reaction{'CH2_S + CO2 <=> CH2 + CO2',
   fr={'Arrhenius', A=7.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r86'
}
reaction{'CH2_S + CO2 <=> CO + CH2O',
   fr={'Arrhenius', A=1.40000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r87'
}
reaction{'CH3 + O2 <=> O + CH3O',
   fr={'Arrhenius', A=2.67500e+13, n=0.00000e+00, T_a=2.88000e+04*S},
   label='r88'
}
reaction{'CH3 + O2 <=> OH + CH2O',
   fr={'Arrhenius', A=3.60000e+10, n=0.00000e+00, T_a=8.94000e+03*S},
   label='r89'
}
reaction{'CH3 + H2O2 <=> HO2 + CH4',
   fr={'Arrhenius', A=2.45000e+04, n=2.47000e+00, T_a=5.18000e+03*S},
   label='r90'
}
reaction{'2CH3 ( + M ) <=> C2H6 ( + M )',
   fr={'pressure dependent',
       k_inf={A=2.12000e+16, n=-9.70000e-01, T_a=6.20000e+02*S},
       k_0={A=1.77000e+50, n=-9.67000e+00, T_a=6.22000e+03*S},
       Troe={a=0.5325, T3=151.00, T1=1038.00, T2=4970.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r91'
}
reaction{'2CH3 <=> H + C2H5',
   fr={'Arrhenius', A=4.99000e+12, n=1.00000e-01, T_a=1.06000e+04*S},
   label='r92'
}
reaction{'CH3 + CHO <=> CH4 + CO',
   fr={'Arrhenius', A=2.64800e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r93'
}
reaction{'CH3 + CH2O <=> CHO + CH4',
   fr={'Arrhenius', A=3.32000e+03, n=2.81000e+00, T_a=5.86000e+03*S},
   label='r94'
}
reaction{'CH3 + C2H4 <=> C2H3 + CH4',
   fr={'Arrhenius', A=2.27000e+05, n=2.00000e+00, T_a=9.20000e+03*S},
   label='r95'
}
reaction{'CH3 + C2H6 <=> C2H5 + CH4',
   fr={'Arrhenius', A=6.14000e+06, n=1.74000e+00, T_a=1.04500e+04*S},
   label='r96'
}
reaction{'CHO + H2O <=> H + CO + H2O',
   fr={'Arrhenius', A=2.24400e+18, n=-1.00000e+00, T_a=1.70000e+04*S},
   label='r97'
}
reaction{'CHO + M <=> H + CO + M',
   fr={'Arrhenius', A=1.87000e+17, n=-1.00000e+00, T_a=1.70000e+04*S},
   efficiencies={H2=2.00, H2O=0.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r98'
}
reaction{'CHO + O2 <=> HO2 + CO',
   fr={'Arrhenius', A=7.60000e+12, n=0.00000e+00, T_a=4.00000e+02*S},
   label='r99'
}
reaction{'CH3O + O2 <=> HO2 + CH2O',
   fr={'Arrhenius', A=4.28000e-13, n=7.60000e+00, T_a=-3.53000e+03*S},
   label='r100'
}
reaction{'C2H3 + O2 <=> CHO + CH2O',
   fr={'Arrhenius', A=3.98000e+12, n=0.00000e+00, T_a=-2.40000e+02*S},
   label='r101'
}
reaction{'C2H4 ( + M ) <=> H2 + C2H2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=8.00000e+12, n=4.40000e-01, T_a=8.87700e+04*S},
       k_0={A=7.00000e+50, n=-9.31000e+00, T_a=9.98600e+04*S},
       Troe={a=0.7345, T3=180.00, T1=1035.00, T2=5417.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r102'
}
reaction{'C2H5 + O2 <=> HO2 + C2H4',
   fr={'Arrhenius', A=8.40000e+11, n=0.00000e+00, T_a=3.87500e+03*S},
   label='r103'
}

