-- this file has been automatically generated by chemkin2libgas.py

-- scaling factor, 1/R
S = 1.0/1.987

reaction{'2O + M <=> O2 + M',
   fr={'Arrhenius', A=1.20000e+17, n=-1.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=2.40, H2O=15.40, CH4=2.00, CO=1.75, CO2=3.60, C2H6=3.00, Ar=0.83},
   label='r0'
}
reaction{'O + H + M <=> OH + M',
   fr={'Arrhenius', A=5.00000e+17, n=-1.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r1'
}
reaction{'O + H2 <=> H + OH',
   fr={'Arrhenius', A=3.87000e+04, n=2.70000e+00, T_a=6.26000e+03*S},
   label='r2'
}
reaction{'O + HO2 <=> OH + O2',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r3'
}
reaction{'O + H2O2 <=> OH + HO2',
   fr={'Arrhenius', A=9.63000e+06, n=2.00000e+00, T_a=4.00000e+03*S},
   label='r4'
}
reaction{'O + CH <=> H + CO',
   fr={'Arrhenius', A=5.70000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r5'
}
reaction{'O + CH2 <=> H + CHO',
   fr={'Arrhenius', A=8.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r6'
}
reaction{'O + CH2_S <=> H2 + CO',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r7'
}
reaction{'O + CH2_S <=> H + CHO',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r8'
}
reaction{'O + CH3 <=> H + CH2O',
   fr={'Arrhenius', A=5.06000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r9'
}
reaction{'O + CH4 <=> OH + CH3',
   fr={'Arrhenius', A=1.02000e+09, n=1.50000e+00, T_a=8.60000e+03*S},
   label='r10'
}
reaction{'O + CO ( + M ) <=> CO2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.80000e+10, n=0.00000e+00, T_a=2.38500e+03*S},
       k_0={A=6.02000e+14, n=0.00000e+00, T_a=3.00000e+03*S},
   },
   efficiencies={H2=2.00, O2=6.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=3.50, C2H6=3.00, Ar=0.50},
   label='r11'
}
reaction{'O + CHO <=> OH + CO',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r12'
}
reaction{'O + CHO <=> H + CO2',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r13'
}
reaction{'O + CH2O <=> OH + CHO',
   fr={'Arrhenius', A=3.90000e+13, n=0.00000e+00, T_a=3.54000e+03*S},
   label='r14'
}
reaction{'O + CH2OH <=> OH + CH2O',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r15'
}
reaction{'O + CH3O <=> OH + CH2O',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r16'
}
reaction{'O + CH3OH <=> OH + CH2OH',
   fr={'Arrhenius', A=3.88000e+05, n=2.50000e+00, T_a=3.10000e+03*S},
   label='r17'
}
reaction{'O + CH3OH <=> OH + CH3O',
   fr={'Arrhenius', A=1.30000e+05, n=2.50000e+00, T_a=5.00000e+03*S},
   label='r18'
}
reaction{'O + C2H <=> CH + CO',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r19'
}
reaction{'O + C2H2 <=> H + HCCO',
   fr={'Arrhenius', A=1.35000e+07, n=2.00000e+00, T_a=1.90000e+03*S},
   label='r20'
}
reaction{'O + C2H2 <=> OH + C2H',
   fr={'Arrhenius', A=4.60000e+19, n=-1.41000e+00, T_a=2.89500e+04*S},
   label='r21'
}
reaction{'O + C2H2 <=> CO + CH2',
   fr={'Arrhenius', A=6.94000e+06, n=2.00000e+00, T_a=1.90000e+03*S},
   label='r22'
}
reaction{'O + C2H3 <=> H + CH2CO',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r23'
}
reaction{'O + C2H4 <=> CH3 + CHO',
   fr={'Arrhenius', A=1.25000e+07, n=1.83000e+00, T_a=2.20000e+02*S},
   label='r24'
}
reaction{'O + C2H5 <=> CH3 + CH2O',
   fr={'Arrhenius', A=2.24000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r25'
}
reaction{'O + C2H6 <=> OH + C2H5',
   fr={'Arrhenius', A=8.98000e+07, n=1.92000e+00, T_a=5.69000e+03*S},
   label='r26'
}
reaction{'O + HCCO <=> H + 2CO',
   fr={'Arrhenius', A=1.00000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r27'
}
reaction{'O + CH2CO <=> OH + HCCO',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=8.00000e+03*S},
   label='r28'
}
reaction{'O + CH2CO <=> CH2 + CO2',
   fr={'Arrhenius', A=1.75000e+12, n=0.00000e+00, T_a=1.35000e+03*S},
   label='r29'
}
reaction{'O2 + CO <=> O + CO2',
   fr={'Arrhenius', A=2.50000e+12, n=0.00000e+00, T_a=4.78000e+04*S},
   label='r30'
}
reaction{'O2 + CH2O <=> HO2 + CHO',
   fr={'Arrhenius', A=1.00000e+14, n=0.00000e+00, T_a=4.00000e+04*S},
   label='r31'
}
reaction{'H + O2 + M <=> HO2 + M',
   fr={'Arrhenius', A=2.80000e+18, n=-8.60000e-01, T_a=0.00000e+00*S},
   efficiencies={O2=0.00, H2O=0.00, CO=0.75, CO2=1.50, C2H6=1.50, N2=0.00, Ar=0.00},
   label='r32'
}
reaction{'H + 2O2 <=> HO2 + O2',
   fr={'Arrhenius', A=2.08000e+19, n=-1.24000e+00, T_a=0.00000e+00*S},
   label='r33'
}
reaction{'H + O2 + H2O <=> HO2 + H2O',
   fr={'Arrhenius', A=1.12600e+19, n=-7.60000e-01, T_a=0.00000e+00*S},
   label='r34'
}
reaction{'H + O2 + N2 <=> HO2 + N2',
   fr={'Arrhenius', A=2.60000e+19, n=-1.24000e+00, T_a=0.00000e+00*S},
   label='r35'
}
reaction{'H + O2 + Ar <=> HO2 + Ar',
   fr={'Arrhenius', A=7.00000e+17, n=-8.00000e-01, T_a=0.00000e+00*S},
   label='r36'
}
reaction{'H + O2 <=> O + OH',
   fr={'Arrhenius', A=2.65000e+16, n=-6.70700e-01, T_a=1.70410e+04*S},
   label='r37'
}
reaction{'2H + M <=> H2 + M',
   fr={'Arrhenius', A=1.00000e+18, n=-1.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=0.00, H2O=0.00, CH4=2.00, CO2=0.00, C2H6=3.00, Ar=0.63},
   label='r38'
}
reaction{'2H + H2 <=> 2H2',
   fr={'Arrhenius', A=9.00000e+16, n=-6.00000e-01, T_a=0.00000e+00*S},
   label='r39'
}
reaction{'2H + H2O <=> H2 + H2O',
   fr={'Arrhenius', A=6.00000e+19, n=-1.25000e+00, T_a=0.00000e+00*S},
   label='r40'
}
reaction{'2H + CO2 <=> H2 + CO2',
   fr={'Arrhenius', A=5.50000e+20, n=-2.00000e+00, T_a=0.00000e+00*S},
   label='r41'
}
reaction{'H + OH + M <=> H2O + M',
   fr={'Arrhenius', A=2.20000e+22, n=-2.00000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=0.73, H2O=3.65, CH4=2.00, C2H6=3.00, Ar=0.38},
   label='r42'
}
reaction{'H + HO2 <=> O + H2O',
   fr={'Arrhenius', A=3.97000e+12, n=0.00000e+00, T_a=6.71000e+02*S},
   label='r43'
}
reaction{'H + HO2 <=> O2 + H2',
   fr={'Arrhenius', A=4.48000e+13, n=0.00000e+00, T_a=1.06800e+03*S},
   label='r44'
}
reaction{'H + HO2 <=> 2OH',
   fr={'Arrhenius', A=8.40000e+13, n=0.00000e+00, T_a=6.35000e+02*S},
   label='r45'
}
reaction{'H + H2O2 <=> HO2 + H2',
   fr={'Arrhenius', A=1.21000e+07, n=2.00000e+00, T_a=5.20000e+03*S},
   label='r46'
}
reaction{'H + H2O2 <=> OH + H2O',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=3.60000e+03*S},
   label='r47'
}
reaction{'H + CH <=> C + H2',
   fr={'Arrhenius', A=1.65000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r48'
}
reaction{'H + CH2 ( + M ) <=> CH3 ( + M )',
   fr={'pressure dependent',
       k_inf={A=6.00000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
       k_0={A=1.04000e+26, n=-2.76000e+00, T_a=1.60000e+03*S},
       Troe={a=.5620, T3=91.00, T1=5836.00, T2=8552.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r49'
}
reaction{'H + CH2_S <=> CH + H2',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r50'
}
reaction{'H + CH3 ( + M ) <=> CH4 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.39000e+16, n=-5.34000e-01, T_a=5.36000e+02*S},
       k_0={A=2.62000e+33, n=-4.76000e+00, T_a=2.44000e+03*S},
       Troe={a=.7830, T3=74.00, T1=2941.00, T2=6964.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=3.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r51'
}
reaction{'H + CH4 <=> CH3 + H2',
   fr={'Arrhenius', A=6.60000e+08, n=1.62000e+00, T_a=1.08400e+04*S},
   label='r52'
}
reaction{'H + CHO ( + M ) <=> CH2O ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.09000e+12, n=4.80000e-01, T_a=-2.60000e+02*S},
       k_0={A=2.47000e+24, n=-2.57000e+00, T_a=4.25000e+02*S},
       Troe={a=.7824, T3=271.00, T1=2755.00, T2=6570.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r53'
}
reaction{'H + CHO <=> H2 + CO',
   fr={'Arrhenius', A=7.34000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r54'
}
reaction{'H + CH2O ( + M ) <=> CH2OH ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.40000e+11, n=4.54000e-01, T_a=3.60000e+03*S},
       k_0={A=1.27000e+32, n=-4.82000e+00, T_a=6.53000e+03*S},
       Troe={a=.7187, T3=103.00, T1=1291.00, T2=4160.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r55'
}
reaction{'H + CH2O ( + M ) <=> CH3O ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.40000e+11, n=4.54000e-01, T_a=2.60000e+03*S},
       k_0={A=2.20000e+30, n=-4.80000e+00, T_a=5.56000e+03*S},
       Troe={a=.7580, T3=94.00, T1=1555.00, T2=4200.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r56'
}
reaction{'H + CH2O <=> CHO + H2',
   fr={'Arrhenius', A=5.74000e+07, n=1.90000e+00, T_a=2.74200e+03*S},
   label='r57'
}
reaction{'H + CH2OH ( + M ) <=> CH3OH ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.05500e+12, n=5.00000e-01, T_a=8.60000e+01*S},
       k_0={A=4.36000e+31, n=-4.65000e+00, T_a=5.08000e+03*S},
       Troe={a=.600, T3=100.00, T1=90000.0, T2=10000.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r58'
}
reaction{'H + CH2OH <=> H2 + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r59'
}
reaction{'H + CH2OH <=> OH + CH3',
   fr={'Arrhenius', A=1.65000e+11, n=6.50000e-01, T_a=-2.84000e+02*S},
   label='r60'
}
reaction{'H + CH2OH <=> CH2_S + H2O',
   fr={'Arrhenius', A=3.28000e+13, n=-9.00000e-02, T_a=6.10000e+02*S},
   label='r61'
}
reaction{'H + CH3O ( + M ) <=> CH3OH ( + M )',
   fr={'pressure dependent',
       k_inf={A=2.43000e+12, n=5.15000e-01, T_a=5.00000e+01*S},
       k_0={A=4.66000e+41, n=-7.44000e+00, T_a=1.40800e+04*S},
       Troe={a=.700, T3=100.00, T1=90000.0, T2=10000.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r62'
}
reaction{'H + CH3O <=> H + CH2OH',
   fr={'Arrhenius', A=4.15000e+07, n=1.63000e+00, T_a=1.92400e+03*S},
   label='r63'
}
reaction{'H + CH3O <=> H2 + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r64'
}
reaction{'H + CH3O <=> OH + CH3',
   fr={'Arrhenius', A=1.50000e+12, n=5.00000e-01, T_a=-1.10000e+02*S},
   label='r65'
}
reaction{'H + CH3O <=> CH2_S + H2O',
   fr={'Arrhenius', A=2.62000e+14, n=-2.30000e-01, T_a=1.07000e+03*S},
   label='r66'
}
reaction{'H + CH3OH <=> CH2OH + H2',
   fr={'Arrhenius', A=1.70000e+07, n=2.10000e+00, T_a=4.87000e+03*S},
   label='r67'
}
reaction{'H + CH3OH <=> CH3O + H2',
   fr={'Arrhenius', A=4.20000e+06, n=2.10000e+00, T_a=4.87000e+03*S},
   label='r68'
}
reaction{'H + C2H ( + M ) <=> C2H2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.00000e+17, n=-1.00000e+00, T_a=0.00000e+00*S},
       k_0={A=3.75000e+33, n=-4.80000e+00, T_a=1.90000e+03*S},
       Troe={a=.6464, T3=132.00, T1=1315.00, T2=5566.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r69'
}
reaction{'H + C2H2 ( + M ) <=> C2H3 ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.60000e+12, n=0.00000e+00, T_a=2.40000e+03*S},
       k_0={A=3.80000e+40, n=-7.27000e+00, T_a=7.22000e+03*S},
       Troe={a=.7507, T3=98.50, T1=1302.00, T2=4167.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r70'
}
reaction{'H + C2H3 ( + M ) <=> C2H4 ( + M )',
   fr={'pressure dependent',
       k_inf={A=6.08000e+12, n=2.70000e-01, T_a=2.80000e+02*S},
       k_0={A=1.40000e+30, n=-3.86000e+00, T_a=3.32000e+03*S},
       Troe={a=.7820, T3=207.50, T1=2663.00, T2=6095.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r71'
}
reaction{'H + C2H3 <=> H2 + C2H2',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r72'
}
reaction{'H + C2H4 ( + M ) <=> C2H5 ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.40000e+11, n=4.54000e-01, T_a=1.82000e+03*S},
       k_0={A=6.00000e+41, n=-7.62000e+00, T_a=6.97000e+03*S},
       Troe={a=.9753, T3=210.00, T1=984.00, T2=4374.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r73'
}
reaction{'H + C2H4 <=> C2H3 + H2',
   fr={'Arrhenius', A=1.32500e+06, n=2.53000e+00, T_a=1.22400e+04*S},
   label='r74'
}
reaction{'H + C2H5 ( + M ) <=> C2H6 ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.21000e+17, n=-9.90000e-01, T_a=1.58000e+03*S},
       k_0={A=1.99000e+41, n=-7.08000e+00, T_a=6.68500e+03*S},
       Troe={a=.8422, T3=125.00, T1=2219.00, T2=6882.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r75'
}
reaction{'H + C2H5 <=> H2 + C2H4',
   fr={'Arrhenius', A=2.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r76'
}
reaction{'H + C2H6 <=> C2H5 + H2',
   fr={'Arrhenius', A=1.15000e+08, n=1.90000e+00, T_a=7.53000e+03*S},
   label='r77'
}
reaction{'H + HCCO <=> CH2_S + CO',
   fr={'Arrhenius', A=1.00000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r78'
}
reaction{'H + CH2CO <=> HCCO + H2',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=8.00000e+03*S},
   label='r79'
}
reaction{'H + CH2CO <=> CH3 + CO',
   fr={'Arrhenius', A=1.13000e+13, n=0.00000e+00, T_a=3.42800e+03*S},
   label='r80'
}
reaction{'H + HCCOH <=> H + CH2CO',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r81'
}
reaction{'H2 + CO ( + M ) <=> CH2O ( + M )',
   fr={'pressure dependent',
       k_inf={A=4.30000e+07, n=1.50000e+00, T_a=7.96000e+04*S},
       k_0={A=5.07000e+27, n=-3.42000e+00, T_a=8.43500e+04*S},
       Troe={a=.9320, T3=197.00, T1=1540.00, T2=10300.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r82'
}
reaction{'OH + H2 <=> H + H2O',
   fr={'Arrhenius', A=2.16000e+08, n=1.51000e+00, T_a=3.43000e+03*S},
   label='r83'
}
reaction{'2OH ( + M ) <=> H2O2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=7.40000e+13, n=-3.70000e-01, T_a=0.00000e+00*S},
       k_0={A=2.30000e+18, n=-9.00000e-01, T_a=-1.70000e+03*S},
       Troe={a=.7346, T3=94.00, T1=1756.00, T2=5182.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r84'
}
reaction{'2OH <=> O + H2O',
   fr={'Arrhenius', A=3.57000e+04, n=2.40000e+00, T_a=-2.11000e+03*S},
   label='r85'
}
reaction{'OH + HO2 <=> O2 + H2O',
   fr={'Arrhenius', A=1.45000e+13, n=0.00000e+00, T_a=-5.00000e+02*S},
   label='r86'
}
-- duplicate reaction found, including...
reaction{'OH + H2O2 <=> HO2 + H2O',
   fr={'Arrhenius', A=2.00000e+12, n=0.00000e+00, T_a=4.27000e+02*S},
   label='r87'
}
-- duplicate reaction found, including...
reaction{'OH + H2O2 <=> HO2 + H2O',
   fr={'Arrhenius', A=1.70000e+18, n=0.00000e+00, T_a=2.94100e+04*S},
   label='r88'
}
-- duplicate reaction found, including...
reaction{'OH + C <=> H + CO',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r89'
}
reaction{'OH + CH <=> H + CHO',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r90'
}
reaction{'OH + CH2 <=> H + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r91'
}
reaction{'OH + CH2 <=> CH + H2O',
   fr={'Arrhenius', A=1.13000e+07, n=2.00000e+00, T_a=3.00000e+03*S},
   label='r92'
}
reaction{'OH + CH2_S <=> H + CH2O',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r93'
}
reaction{'OH + CH3 ( + M ) <=> CH3OH ( + M )',
   fr={'pressure dependent',
       k_inf={A=2.79000e+18, n=-1.43000e+00, T_a=1.33000e+03*S},
       k_0={A=4.00000e+36, n=-5.92000e+00, T_a=3.14000e+03*S},
       Troe={a=.4120, T3=195.0, T1=5900.00, T2=6394.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r94'
}
reaction{'OH + CH3 <=> CH2 + H2O',
   fr={'Arrhenius', A=5.60000e+07, n=1.60000e+00, T_a=5.42000e+03*S},
   label='r95'
}
reaction{'OH + CH3 <=> CH2_S + H2O',
   fr={'Arrhenius', A=6.44000e+17, n=-1.34000e+00, T_a=1.41700e+03*S},
   label='r96'
}
reaction{'OH + CH4 <=> CH3 + H2O',
   fr={'Arrhenius', A=1.00000e+08, n=1.60000e+00, T_a=3.12000e+03*S},
   label='r97'
}
reaction{'OH + CO <=> H + CO2',
   fr={'Arrhenius', A=4.76000e+07, n=1.22800e+00, T_a=7.00000e+01*S},
   label='r98'
}
reaction{'OH + CHO <=> H2O + CO',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r99'
}
reaction{'OH + CH2O <=> CHO + H2O',
   fr={'Arrhenius', A=3.43000e+09, n=1.18000e+00, T_a=-4.47000e+02*S},
   label='r100'
}
reaction{'OH + CH2OH <=> H2O + CH2O',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r101'
}
reaction{'OH + CH3O <=> H2O + CH2O',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r102'
}
reaction{'OH + CH3OH <=> CH2OH + H2O',
   fr={'Arrhenius', A=1.44000e+06, n=2.00000e+00, T_a=-8.40000e+02*S},
   label='r103'
}
reaction{'OH + CH3OH <=> CH3O + H2O',
   fr={'Arrhenius', A=6.30000e+06, n=2.00000e+00, T_a=1.50000e+03*S},
   label='r104'
}
reaction{'OH + C2H <=> H + HCCO',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r105'
}
reaction{'OH + C2H2 <=> H + CH2CO',
   fr={'Arrhenius', A=2.18000e-04, n=4.50000e+00, T_a=-1.00000e+03*S},
   label='r106'
}
reaction{'OH + C2H2 <=> H + HCCOH',
   fr={'Arrhenius', A=5.04000e+05, n=2.30000e+00, T_a=1.35000e+04*S},
   label='r107'
}
reaction{'OH + C2H2 <=> C2H + H2O',
   fr={'Arrhenius', A=3.37000e+07, n=2.00000e+00, T_a=1.40000e+04*S},
   label='r108'
}
reaction{'OH + C2H2 <=> CH3 + CO',
   fr={'Arrhenius', A=4.83000e-04, n=4.00000e+00, T_a=-2.00000e+03*S},
   label='r109'
}
reaction{'OH + C2H3 <=> H2O + C2H2',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r110'
}
reaction{'OH + C2H4 <=> C2H3 + H2O',
   fr={'Arrhenius', A=3.60000e+06, n=2.00000e+00, T_a=2.50000e+03*S},
   label='r111'
}
reaction{'OH + C2H6 <=> C2H5 + H2O',
   fr={'Arrhenius', A=3.54000e+06, n=2.12000e+00, T_a=8.70000e+02*S},
   label='r112'
}
reaction{'OH + CH2CO <=> HCCO + H2O',
   fr={'Arrhenius', A=7.50000e+12, n=0.00000e+00, T_a=2.00000e+03*S},
   label='r113'
}
reaction{'2HO2 <=> O2 + H2O2',
   fr={'Arrhenius', A=1.30000e+11, n=0.00000e+00, T_a=-1.63000e+03*S},
   label='r114'
}
-- duplicate reaction found, including...
reaction{'2HO2 <=> O2 + H2O2',
   fr={'Arrhenius', A=4.20000e+14, n=0.00000e+00, T_a=1.20000e+04*S},
   label='r115'
}
-- duplicate reaction found, including...
reaction{'HO2 + CH2 <=> OH + CH2O',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r116'
}
reaction{'HO2 + CH3 <=> O2 + CH4',
   fr={'Arrhenius', A=1.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r117'
}
reaction{'HO2 + CH3 <=> OH + CH3O',
   fr={'Arrhenius', A=3.78000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r118'
}
reaction{'HO2 + CO <=> OH + CO2',
   fr={'Arrhenius', A=1.50000e+14, n=0.00000e+00, T_a=2.36000e+04*S},
   label='r119'
}
reaction{'HO2 + CH2O <=> CHO + H2O2',
   fr={'Arrhenius', A=5.60000e+06, n=2.00000e+00, T_a=1.20000e+04*S},
   label='r120'
}
reaction{'C + O2 <=> O + CO',
   fr={'Arrhenius', A=5.80000e+13, n=0.00000e+00, T_a=5.76000e+02*S},
   label='r121'
}
reaction{'C + CH2 <=> H + C2H',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r122'
}
reaction{'C + CH3 <=> H + C2H2',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r123'
}
reaction{'CH + O2 <=> O + CHO',
   fr={'Arrhenius', A=6.71000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r124'
}
reaction{'CH + H2 <=> H + CH2',
   fr={'Arrhenius', A=1.08000e+14, n=0.00000e+00, T_a=3.11000e+03*S},
   label='r125'
}
reaction{'CH + H2O <=> H + CH2O',
   fr={'Arrhenius', A=5.71000e+12, n=0.00000e+00, T_a=-7.55000e+02*S},
   label='r126'
}
reaction{'CH + CH2 <=> H + C2H2',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r127'
}
reaction{'CH + CH3 <=> H + C2H3',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r128'
}
reaction{'CH + CH4 <=> H + C2H4',
   fr={'Arrhenius', A=6.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r129'
}
reaction{'CH + CO ( + M ) <=> HCCO ( + M )',
   fr={'pressure dependent',
       k_inf={A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
       k_0={A=2.69000e+28, n=-3.74000e+00, T_a=1.93600e+03*S},
       Troe={a=.5757, T3=237.00, T1=1652.00, T2=5069.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r130'
}
reaction{'CH + CO2 <=> CHO + CO',
   fr={'Arrhenius', A=1.90000e+14, n=0.00000e+00, T_a=1.57920e+04*S},
   label='r131'
}
reaction{'CH + CH2O <=> H + CH2CO',
   fr={'Arrhenius', A=9.46000e+13, n=0.00000e+00, T_a=-5.15000e+02*S},
   label='r132'
}
reaction{'CH + HCCO <=> CO + C2H2',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r133'
}
reaction{'CH2 + O2=> OH + H + CO',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=1.50000e+03*S},
   label='r134'
}
reaction{'CH2 + H2 <=> H + CH3',
   fr={'Arrhenius', A=5.00000e+05, n=2.00000e+00, T_a=7.23000e+03*S},
   label='r135'
}
reaction{'2CH2 <=> H2 + C2H2',
   fr={'Arrhenius', A=1.60000e+15, n=0.00000e+00, T_a=1.19440e+04*S},
   label='r136'
}
reaction{'CH2 + CH3 <=> H + C2H4',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r137'
}
reaction{'CH2 + CH4 <=> 2CH3',
   fr={'Arrhenius', A=2.46000e+06, n=2.00000e+00, T_a=8.27000e+03*S},
   label='r138'
}
reaction{'CH2 + CO ( + M ) <=> CH2CO ( + M )',
   fr={'pressure dependent',
       k_inf={A=8.10000e+11, n=5.00000e-01, T_a=4.51000e+03*S},
       k_0={A=2.69000e+33, n=-5.11000e+00, T_a=7.09500e+03*S},
       Troe={a=.5907, T3=275.00, T1=1226.00, T2=5185.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r139'
}
reaction{'CH2 + HCCO <=> C2H3 + CO',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r140'
}
reaction{'CH2_S + N2 <=> CH2 + N2',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=6.00000e+02*S},
   label='r141'
}
reaction{'CH2_S + Ar <=> CH2 + Ar',
   fr={'Arrhenius', A=9.00000e+12, n=0.00000e+00, T_a=6.00000e+02*S},
   label='r142'
}
reaction{'CH2_S + O2 <=> H + OH + CO',
   fr={'Arrhenius', A=2.80000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r143'
}
reaction{'CH2_S + O2 <=> CO + H2O',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r144'
}
reaction{'CH2_S + H2 <=> CH3 + H',
   fr={'Arrhenius', A=7.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r145'
}
reaction{'CH2_S + H2O ( + M ) <=> CH3OH ( + M )',
   fr={'pressure dependent',
       k_inf={A=4.82000e+17, n=-1.16000e+00, T_a=1.14500e+03*S},
       k_0={A=1.88000e+38, n=-6.36000e+00, T_a=5.04000e+03*S},
       Troe={a=.6027, T3=208.00, T1=3922.00, T2=10180.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r146'
}
reaction{'CH2_S + H2O <=> CH2 + H2O',
   fr={'Arrhenius', A=3.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r147'
}
reaction{'CH2_S + CH3 <=> H + C2H4',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=-5.70000e+02*S},
   label='r148'
}
reaction{'CH2_S + CH4 <=> 2CH3',
   fr={'Arrhenius', A=1.60000e+13, n=0.00000e+00, T_a=-5.70000e+02*S},
   label='r149'
}
reaction{'CH2_S + CO <=> CH2 + CO',
   fr={'Arrhenius', A=9.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r150'
}
reaction{'CH2_S + CO2 <=> CH2 + CO2',
   fr={'Arrhenius', A=7.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r151'
}
reaction{'CH2_S + CO2 <=> CO + CH2O',
   fr={'Arrhenius', A=1.40000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r152'
}
reaction{'CH2_S + C2H6 <=> CH3 + C2H5',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=-5.50000e+02*S},
   label='r153'
}
reaction{'CH3 + O2 <=> O + CH3O',
   fr={'Arrhenius', A=3.56000e+13, n=0.00000e+00, T_a=3.04800e+04*S},
   label='r154'
}
reaction{'CH3 + O2 <=> OH + CH2O',
   fr={'Arrhenius', A=2.31000e+12, n=0.00000e+00, T_a=2.03150e+04*S},
   label='r155'
}
reaction{'CH3 + H2O2 <=> HO2 + CH4',
   fr={'Arrhenius', A=2.45000e+04, n=2.47000e+00, T_a=5.18000e+03*S},
   label='r156'
}
reaction{'2CH3 ( + M ) <=> C2H6 ( + M )',
   fr={'pressure dependent',
       k_inf={A=6.77000e+16, n=-1.18000e+00, T_a=6.54000e+02*S},
       k_0={A=3.40000e+41, n=-7.03000e+00, T_a=2.76200e+03*S},
       Troe={a=.6190, T3=73.20, T1=1180.00, T2=9999.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r157'
}
reaction{'2CH3 <=> H + C2H5',
   fr={'Arrhenius', A=6.84000e+12, n=1.00000e-01, T_a=1.06000e+04*S},
   label='r158'
}
reaction{'CH3 + CHO <=> CH4 + CO',
   fr={'Arrhenius', A=2.64800e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r159'
}
reaction{'CH3 + CH2O <=> CHO + CH4',
   fr={'Arrhenius', A=3.32000e+03, n=2.81000e+00, T_a=5.86000e+03*S},
   label='r160'
}
reaction{'CH3 + CH3OH <=> CH2OH + CH4',
   fr={'Arrhenius', A=3.00000e+07, n=1.50000e+00, T_a=9.94000e+03*S},
   label='r161'
}
reaction{'CH3 + CH3OH <=> CH3O + CH4',
   fr={'Arrhenius', A=1.00000e+07, n=1.50000e+00, T_a=9.94000e+03*S},
   label='r162'
}
reaction{'CH3 + C2H4 <=> C2H3 + CH4',
   fr={'Arrhenius', A=2.27000e+05, n=2.00000e+00, T_a=9.20000e+03*S},
   label='r163'
}
reaction{'CH3 + C2H6 <=> C2H5 + CH4',
   fr={'Arrhenius', A=6.14000e+06, n=1.74000e+00, T_a=1.04500e+04*S},
   label='r164'
}
reaction{'CHO + H2O <=> H + CO + H2O',
   fr={'Arrhenius', A=1.50000e+18, n=-1.00000e+00, T_a=1.70000e+04*S},
   label='r165'
}
reaction{'CHO + M <=> H + CO + M',
   fr={'Arrhenius', A=1.87000e+17, n=-1.00000e+00, T_a=1.70000e+04*S},
   efficiencies={H2=2.00, H2O=0.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00},
   label='r166'
}
reaction{'CHO + O2 <=> HO2 + CO',
   fr={'Arrhenius', A=1.34500e+13, n=0.00000e+00, T_a=4.00000e+02*S},
   label='r167'
}
reaction{'CH2OH + O2 <=> HO2 + CH2O',
   fr={'Arrhenius', A=1.80000e+13, n=0.00000e+00, T_a=9.00000e+02*S},
   label='r168'
}
reaction{'CH3O + O2 <=> HO2 + CH2O',
   fr={'Arrhenius', A=4.28000e-13, n=7.60000e+00, T_a=-3.53000e+03*S},
   label='r169'
}
reaction{'C2H + O2 <=> CHO + CO',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=-7.55000e+02*S},
   label='r170'
}
reaction{'C2H + H2 <=> H + C2H2',
   fr={'Arrhenius', A=5.68000e+10, n=9.00000e-01, T_a=1.99300e+03*S},
   label='r171'
}
reaction{'C2H3 + O2 <=> CHO + CH2O',
   fr={'Arrhenius', A=4.58000e+16, n=-1.39000e+00, T_a=1.01500e+03*S},
   label='r172'
}
reaction{'C2H4 ( + M ) <=> H2 + C2H2 ( + M )',
   fr={'pressure dependent',
       k_inf={A=8.00000e+12, n=4.40000e-01, T_a=8.67700e+04*S},
       k_0={A=1.58000e+51, n=-9.30000e+00, T_a=9.78000e+04*S},
       Troe={a=.7345, T3=180.00, T1=1035.00, T2=5417.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r173'
}
reaction{'C2H5 + O2 <=> HO2 + C2H4',
   fr={'Arrhenius', A=8.40000e+11, n=0.00000e+00, T_a=3.87500e+03*S},
   label='r174'
}
reaction{'HCCO + O2 <=> OH + 2CO',
   fr={'Arrhenius', A=3.20000e+12, n=0.00000e+00, T_a=8.54000e+02*S},
   label='r175'
}
reaction{'2HCCO <=> 2CO + C2H2',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r176'
}
reaction{'N + NO <=> N2 + O',
   fr={'Arrhenius', A=2.70000e+13, n=0.00000e+00, T_a=3.55000e+02*S},
   label='r177'
}
reaction{'N + O2 <=> NO + O',
   fr={'Arrhenius', A=9.00000e+09, n=1.00000e+00, T_a=6.50000e+03*S},
   label='r178'
}
reaction{'N + OH <=> NO + H',
   fr={'Arrhenius', A=3.36000e+13, n=0.00000e+00, T_a=3.85000e+02*S},
   label='r179'
}
reaction{'N2O + O <=> N2 + O2',
   fr={'Arrhenius', A=1.40000e+12, n=0.00000e+00, T_a=1.08100e+04*S},
   label='r180'
}
reaction{'N2O + O <=> 2NO',
   fr={'Arrhenius', A=2.90000e+13, n=0.00000e+00, T_a=2.31500e+04*S},
   label='r181'
}
reaction{'N2O + H <=> N2 + OH',
   fr={'Arrhenius', A=3.87000e+14, n=0.00000e+00, T_a=1.88800e+04*S},
   label='r182'
}
reaction{'N2O + OH <=> N2 + HO2',
   fr={'Arrhenius', A=2.00000e+12, n=0.00000e+00, T_a=2.10600e+04*S},
   label='r183'
}
reaction{'N2O ( + M ) <=> N2 + O ( + M )',
   fr={'pressure dependent',
       k_inf={A=7.91000e+10, n=0.00000e+00, T_a=5.60200e+04*S},
       k_0={A=6.37000e+14, n=0.00000e+00, T_a=5.66400e+04*S},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.62},
   label='r184'
}
reaction{'HO2 + NO <=> NO2 + OH',
   fr={'Arrhenius', A=2.11000e+12, n=0.00000e+00, T_a=-4.80000e+02*S},
   label='r185'
}
reaction{'NO + O + M <=> NO2 + M',
   fr={'Arrhenius', A=1.06000e+20, n=-1.41000e+00, T_a=0.00000e+00*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r186'
}
reaction{'NO2 + O <=> NO + O2',
   fr={'Arrhenius', A=3.90000e+12, n=0.00000e+00, T_a=-2.40000e+02*S},
   label='r187'
}
reaction{'NO2 + H <=> NO + OH',
   fr={'Arrhenius', A=1.32000e+14, n=0.00000e+00, T_a=3.60000e+02*S},
   label='r188'
}
reaction{'NH + O <=> NO + H',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r189'
}
reaction{'NH + H <=> N + H2',
   fr={'Arrhenius', A=3.20000e+13, n=0.00000e+00, T_a=3.30000e+02*S},
   label='r190'
}
reaction{'NH + OH <=> HNO + H',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r191'
}
reaction{'NH + OH <=> N + H2O',
   fr={'Arrhenius', A=2.00000e+09, n=1.20000e+00, T_a=0.00000e+00*S},
   label='r192'
}
reaction{'NH + O2 <=> HNO + O',
   fr={'Arrhenius', A=4.61000e+05, n=2.00000e+00, T_a=6.50000e+03*S},
   label='r193'
}
reaction{'NH + O2 <=> NO + OH',
   fr={'Arrhenius', A=1.28000e+06, n=1.50000e+00, T_a=1.00000e+02*S},
   label='r194'
}
reaction{'NH + N <=> N2 + H',
   fr={'Arrhenius', A=1.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r195'
}
reaction{'NH + H2O <=> HNO + H2',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=1.38500e+04*S},
   label='r196'
}
reaction{'NH + NO <=> N2 + OH',
   fr={'Arrhenius', A=2.16000e+13, n=-2.30000e-01, T_a=0.00000e+00*S},
   label='r197'
}
reaction{'NH + NO <=> N2O + H',
   fr={'Arrhenius', A=3.65000e+14, n=-4.50000e-01, T_a=0.00000e+00*S},
   label='r198'
}
reaction{'NH2 + O <=> OH + NH',
   fr={'Arrhenius', A=3.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r199'
}
reaction{'NH2 + O <=> H + HNO',
   fr={'Arrhenius', A=3.90000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r200'
}
reaction{'NH2 + H <=> NH + H2',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=3.65000e+03*S},
   label='r201'
}
reaction{'NH2 + OH <=> NH + H2O',
   fr={'Arrhenius', A=9.00000e+07, n=1.50000e+00, T_a=-4.60000e+02*S},
   label='r202'
}
reaction{'NNH <=> N2 + H',
   fr={'Arrhenius', A=3.30000e+08, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r203'
}
reaction{'NNH + M <=> N2 + H + M',
   fr={'Arrhenius', A=1.30000e+14, n=-1.10000e-01, T_a=4.98000e+03*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r204'
}
reaction{'NNH + O2 <=> HO2 + N2',
   fr={'Arrhenius', A=5.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r205'
}
reaction{'NNH + O <=> OH + N2',
   fr={'Arrhenius', A=2.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r206'
}
reaction{'NNH + O <=> NH + NO',
   fr={'Arrhenius', A=7.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r207'
}
reaction{'NNH + H <=> H2 + N2',
   fr={'Arrhenius', A=5.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r208'
}
reaction{'NNH + OH <=> H2O + N2',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r209'
}
reaction{'NNH + CH3 <=> CH4 + N2',
   fr={'Arrhenius', A=2.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r210'
}
reaction{'H + NO + M <=> HNO + M',
   fr={'Arrhenius', A=4.48000e+19, n=-1.32000e+00, T_a=7.40000e+02*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r211'
}
reaction{'HNO + O <=> NO + OH',
   fr={'Arrhenius', A=2.50000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r212'
}
reaction{'HNO + H <=> H2 + NO',
   fr={'Arrhenius', A=9.00000e+11, n=7.20000e-01, T_a=6.60000e+02*S},
   label='r213'
}
reaction{'HNO + OH <=> NO + H2O',
   fr={'Arrhenius', A=1.30000e+07, n=1.90000e+00, T_a=-9.50000e+02*S},
   label='r214'
}
reaction{'HNO + O2 <=> HO2 + NO',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=1.30000e+04*S},
   label='r215'
}
reaction{'CN + O <=> CO + N',
   fr={'Arrhenius', A=7.70000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r216'
}
reaction{'CN + OH <=> NCO + H',
   fr={'Arrhenius', A=4.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r217'
}
reaction{'CN + H2O <=> HCN + OH',
   fr={'Arrhenius', A=8.00000e+12, n=0.00000e+00, T_a=7.46000e+03*S},
   label='r218'
}
reaction{'CN + O2 <=> NCO + O',
   fr={'Arrhenius', A=6.14000e+12, n=0.00000e+00, T_a=-4.40000e+02*S},
   label='r219'
}
reaction{'CN + H2 <=> HCN + H',
   fr={'Arrhenius', A=2.95000e+05, n=2.45000e+00, T_a=2.24000e+03*S},
   label='r220'
}
reaction{'NCO + O <=> NO + CO',
   fr={'Arrhenius', A=2.35000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r221'
}
reaction{'NCO + H <=> NH + CO',
   fr={'Arrhenius', A=5.40000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r222'
}
reaction{'NCO + OH <=> NO + H + CO',
   fr={'Arrhenius', A=2.50000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r223'
}
reaction{'NCO + N <=> N2 + CO',
   fr={'Arrhenius', A=2.00000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r224'
}
reaction{'NCO + O2 <=> NO + CO2',
   fr={'Arrhenius', A=2.00000e+12, n=0.00000e+00, T_a=2.00000e+04*S},
   label='r225'
}
reaction{'NCO + M <=> N + CO + M',
   fr={'Arrhenius', A=3.10000e+14, n=0.00000e+00, T_a=5.40500e+04*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r226'
}
reaction{'NCO + NO <=> N2O + CO',
   fr={'Arrhenius', A=1.90000e+17, n=-1.52000e+00, T_a=7.40000e+02*S},
   label='r227'
}
reaction{'NCO + NO <=> N2 + CO2',
   fr={'Arrhenius', A=3.80000e+18, n=-2.00000e+00, T_a=8.00000e+02*S},
   label='r228'
}
reaction{'HCN + M <=> H + CN + M',
   fr={'Arrhenius', A=1.04000e+29, n=-3.30000e+00, T_a=1.26600e+05*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r229'
}
reaction{'HCN + O <=> NCO + H',
   fr={'Arrhenius', A=2.03000e+04, n=2.64000e+00, T_a=4.98000e+03*S},
   label='r230'
}
reaction{'HCN + O <=> NH + CO',
   fr={'Arrhenius', A=5.07000e+03, n=2.64000e+00, T_a=4.98000e+03*S},
   label='r231'
}
reaction{'HCN + O <=> CN + OH',
   fr={'Arrhenius', A=3.91000e+09, n=1.58000e+00, T_a=2.66000e+04*S},
   label='r232'
}
reaction{'HCN + OH <=> HOCN + H',
   fr={'Arrhenius', A=1.10000e+06, n=2.03000e+00, T_a=1.33700e+04*S},
   label='r233'
}
reaction{'HCN + OH <=> HNCO + H',
   fr={'Arrhenius', A=4.40000e+03, n=2.26000e+00, T_a=6.40000e+03*S},
   label='r234'
}
reaction{'HCN + OH <=> NH2 + CO',
   fr={'Arrhenius', A=1.60000e+02, n=2.56000e+00, T_a=9.00000e+03*S},
   label='r235'
}
reaction{'H + HCN ( + M ) <=> H2CN ( + M )',
   fr={'pressure dependent',
       k_inf={A=3.30000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
       k_0={A=1.40000e+26, n=-3.40000e+00, T_a=1.90000e+03*S},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r236'
}
reaction{'H2CN + N <=> N2 + CH2',
   fr={'Arrhenius', A=6.00000e+13, n=0.00000e+00, T_a=4.00000e+02*S},
   label='r237'
}
reaction{'C + N2 <=> CN + N',
   fr={'Arrhenius', A=6.30000e+13, n=0.00000e+00, T_a=4.60200e+04*S},
   label='r238'
}
reaction{'CH + N2 <=> HCN + N',
   fr={'Arrhenius', A=3.12000e+09, n=8.80000e-01, T_a=2.01300e+04*S},
   label='r239'
}
reaction{'CH + N2 ( + M ) <=> HCNN ( + M )',
   fr={'pressure dependent',
       k_inf={A=3.10000e+12, n=1.50000e-01, T_a=0.00000e+00*S},
       k_0={A=1.30000e+25, n=-3.16000e+00, T_a=7.40000e+02*S},
       Troe={a=.6670, T3=235.00, T1=2117.00, T2=4536.00},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=1.00},
   label='r240'
}
reaction{'CH2 + N2 <=> HCN + NH',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=7.40000e+04*S},
   label='r241'
}
reaction{'CH2_S + N2 <=> NH + HCN',
   fr={'Arrhenius', A=1.00000e+11, n=0.00000e+00, T_a=6.50000e+04*S},
   label='r242'
}
reaction{'C + NO <=> CN + O',
   fr={'Arrhenius', A=1.90000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r243'
}
reaction{'C + NO <=> CO + N',
   fr={'Arrhenius', A=2.90000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r244'
}
reaction{'CH + NO <=> HCN + O',
   fr={'Arrhenius', A=4.10000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r245'
}
reaction{'CH + NO <=> H + NCO',
   fr={'Arrhenius', A=1.62000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r246'
}
reaction{'CH + NO <=> N + CHO',
   fr={'Arrhenius', A=2.46000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r247'
}
reaction{'CH2 + NO <=> H + HNCO',
   fr={'Arrhenius', A=3.10000e+17, n=-1.38000e+00, T_a=1.27000e+03*S},
   label='r248'
}
reaction{'CH2 + NO <=> OH + HCN',
   fr={'Arrhenius', A=2.90000e+14, n=-6.90000e-01, T_a=7.60000e+02*S},
   label='r249'
}
reaction{'CH2 + NO <=> H + HCNO',
   fr={'Arrhenius', A=3.80000e+13, n=-3.60000e-01, T_a=5.80000e+02*S},
   label='r250'
}
reaction{'CH2_S + NO <=> H + HNCO',
   fr={'Arrhenius', A=3.10000e+17, n=-1.38000e+00, T_a=1.27000e+03*S},
   label='r251'
}
reaction{'CH2_S + NO <=> OH + HCN',
   fr={'Arrhenius', A=2.90000e+14, n=-6.90000e-01, T_a=7.60000e+02*S},
   label='r252'
}
reaction{'CH2_S + NO <=> H + HCNO',
   fr={'Arrhenius', A=3.80000e+13, n=-3.60000e-01, T_a=5.80000e+02*S},
   label='r253'
}
reaction{'CH3 + NO <=> HCN + H2O',
   fr={'Arrhenius', A=9.60000e+13, n=0.00000e+00, T_a=2.88000e+04*S},
   label='r254'
}
reaction{'CH3 + NO <=> H2CN + OH',
   fr={'Arrhenius', A=1.00000e+12, n=0.00000e+00, T_a=2.17500e+04*S},
   label='r255'
}
reaction{'HCNN + O <=> CO + H + N2',
   fr={'Arrhenius', A=2.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r256'
}
reaction{'HCNN + O <=> HCN + NO',
   fr={'Arrhenius', A=2.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r257'
}
reaction{'HCNN + O2 <=> O + CHO + N2',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r258'
}
reaction{'HCNN + OH <=> H + CHO + N2',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r259'
}
reaction{'HCNN + H <=> CH2 + N2',
   fr={'Arrhenius', A=1.00000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r260'
}
reaction{'HNCO + O <=> NH + CO2',
   fr={'Arrhenius', A=9.80000e+07, n=1.41000e+00, T_a=8.50000e+03*S},
   label='r261'
}
reaction{'HNCO + O <=> HNO + CO',
   fr={'Arrhenius', A=1.50000e+08, n=1.57000e+00, T_a=4.40000e+04*S},
   label='r262'
}
reaction{'HNCO + O <=> NCO + OH',
   fr={'Arrhenius', A=2.20000e+06, n=2.11000e+00, T_a=1.14000e+04*S},
   label='r263'
}
reaction{'HNCO + H <=> NH2 + CO',
   fr={'Arrhenius', A=2.25000e+07, n=1.70000e+00, T_a=3.80000e+03*S},
   label='r264'
}
reaction{'HNCO + H <=> H2 + NCO',
   fr={'Arrhenius', A=1.05000e+05, n=2.50000e+00, T_a=1.33000e+04*S},
   label='r265'
}
reaction{'HNCO + OH <=> NCO + H2O',
   fr={'Arrhenius', A=3.30000e+07, n=1.50000e+00, T_a=3.60000e+03*S},
   label='r266'
}
reaction{'HNCO + OH <=> NH2 + CO2',
   fr={'Arrhenius', A=3.30000e+06, n=1.50000e+00, T_a=3.60000e+03*S},
   label='r267'
}
reaction{'HNCO + M <=> NH + CO + M',
   fr={'Arrhenius', A=1.18000e+16, n=0.00000e+00, T_a=8.47200e+04*S},
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r268'
}
reaction{'HCNO + H <=> H + HNCO',
   fr={'Arrhenius', A=2.10000e+15, n=-6.90000e-01, T_a=2.85000e+03*S},
   label='r269'
}
reaction{'HCNO + H <=> OH + HCN',
   fr={'Arrhenius', A=2.70000e+11, n=1.80000e-01, T_a=2.12000e+03*S},
   label='r270'
}
reaction{'HCNO + H <=> NH2 + CO',
   fr={'Arrhenius', A=1.70000e+14, n=-7.50000e-01, T_a=2.89000e+03*S},
   label='r271'
}
reaction{'HOCN + H <=> H + HNCO',
   fr={'Arrhenius', A=2.00000e+07, n=2.00000e+00, T_a=2.00000e+03*S},
   label='r272'
}
reaction{'HCCO + NO <=> HCNO + CO',
   fr={'Arrhenius', A=9.00000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r273'
}
reaction{'CH3 + N <=> H2CN + H',
   fr={'Arrhenius', A=6.10000e+14, n=-3.10000e-01, T_a=2.90000e+02*S},
   label='r274'
}
reaction{'CH3 + N <=> HCN + H2',
   fr={'Arrhenius', A=3.70000e+12, n=1.50000e-01, T_a=-9.00000e+01*S},
   label='r275'
}
reaction{'NH3 + H <=> NH2 + H2',
   fr={'Arrhenius', A=5.40000e+05, n=2.40000e+00, T_a=9.91500e+03*S},
   label='r276'
}
reaction{'NH3 + OH <=> NH2 + H2O',
   fr={'Arrhenius', A=5.00000e+07, n=1.60000e+00, T_a=9.55000e+02*S},
   label='r277'
}
reaction{'NH3 + O <=> NH2 + OH',
   fr={'Arrhenius', A=9.40000e+06, n=1.94000e+00, T_a=6.46000e+03*S},
   label='r278'
}
reaction{'NH + CO2 <=> HNO + CO',
   fr={'Arrhenius', A=1.00000e+13, n=0.00000e+00, T_a=1.43500e+04*S},
   label='r279'
}
reaction{'CN + NO2 <=> NCO + NO',
   fr={'Arrhenius', A=6.16000e+15, n=-7.52000e-01, T_a=3.45000e+02*S},
   label='r280'
}
reaction{'NCO + NO2 <=> N2O + CO2',
   fr={'Arrhenius', A=3.25000e+12, n=0.00000e+00, T_a=-7.05000e+02*S},
   label='r281'
}
reaction{'N + CO2 <=> NO + CO',
   fr={'Arrhenius', A=3.00000e+12, n=0.00000e+00, T_a=1.13000e+04*S},
   label='r282'
}
reaction{'O + CH3=> H + H2 + CO',
   fr={'Arrhenius', A=3.37000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r283'
}
reaction{'O + C2H4 <=> H + CH2CHO',
   fr={'Arrhenius', A=6.70000e+06, n=1.83000e+00, T_a=2.20000e+02*S},
   label='r284'
}
reaction{'O + C2H5 <=> H + CH3CHO',
   fr={'Arrhenius', A=1.09600e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r285'
}
reaction{'OH + HO2 <=> O2 + H2O',
   fr={'Arrhenius', A=5.00000e+15, n=0.00000e+00, T_a=1.73300e+04*S},
   label='r286'
}
-- duplicate reaction found, including...
reaction{'OH + CH3=> H2 + CH2O',
   fr={'Arrhenius', A=8.00000e+09, n=5.00000e-01, T_a=-1.75500e+03*S},
   label='r287'
}
reaction{'CH + H2 ( + M ) <=> CH3 ( + M )',
   fr={'pressure dependent',
       k_inf={A=1.97000e+12, n=4.30000e-01, T_a=-3.70000e+02*S},
       k_0={A=4.82000e+25, n=-2.80000e+00, T_a=5.90000e+02*S},
       Troe={a=.578, T3=122.0, T1=2535.0, T2=9365.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r288'
}
reaction{'CH2 + O2=> 2H + CO2',
   fr={'Arrhenius', A=5.80000e+12, n=0.00000e+00, T_a=1.50000e+03*S},
   label='r289'
}
reaction{'CH2 + O2 <=> O + CH2O',
   fr={'Arrhenius', A=2.40000e+12, n=0.00000e+00, T_a=1.50000e+03*S},
   label='r290'
}
reaction{'CH2 + CH2=> 2H + C2H2',
   fr={'Arrhenius', A=2.00000e+14, n=0.00000e+00, T_a=1.09890e+04*S},
   label='r291'
}
reaction{'CH2_S + H2O=> H2 + CH2O',
   fr={'Arrhenius', A=6.82000e+10, n=2.50000e-01, T_a=-9.35000e+02*S},
   label='r292'
}
reaction{'C2H3 + O2 <=> O + CH2CHO',
   fr={'Arrhenius', A=3.03000e+11, n=2.90000e-01, T_a=1.10000e+01*S},
   label='r293'
}
reaction{'C2H3 + O2 <=> HO2 + C2H2',
   fr={'Arrhenius', A=1.33700e+06, n=1.61000e+00, T_a=-3.84000e+02*S},
   label='r294'
}
reaction{'O + CH3CHO <=> OH + CH2CHO',
   fr={'Arrhenius', A=2.92000e+12, n=0.00000e+00, T_a=1.80800e+03*S},
   label='r295'
}
reaction{'O + CH3CHO=> OH + CH3 + CO',
   fr={'Arrhenius', A=2.92000e+12, n=0.00000e+00, T_a=1.80800e+03*S},
   label='r296'
}
reaction{'O2 + CH3CHO=> HO2 + CH3 + CO',
   fr={'Arrhenius', A=3.01000e+13, n=0.00000e+00, T_a=3.91500e+04*S},
   label='r297'
}
reaction{'H + CH3CHO <=> CH2CHO + H2',
   fr={'Arrhenius', A=2.05000e+09, n=1.16000e+00, T_a=2.40500e+03*S},
   label='r298'
}
reaction{'H + CH3CHO=> CH3 + H2 + CO',
   fr={'Arrhenius', A=2.05000e+09, n=1.16000e+00, T_a=2.40500e+03*S},
   label='r299'
}
reaction{'OH + CH3CHO=> CH3 + H2O + CO',
   fr={'Arrhenius', A=2.34300e+10, n=7.30000e-01, T_a=-1.11300e+03*S},
   label='r300'
}
reaction{'HO2 + CH3CHO=> CH3 + H2O2 + CO',
   fr={'Arrhenius', A=3.01000e+12, n=0.00000e+00, T_a=1.19230e+04*S},
   label='r301'
}
reaction{'CH3 + CH3CHO=> CH3 + CH4 + CO',
   fr={'Arrhenius', A=2.72000e+06, n=1.77000e+00, T_a=5.92000e+03*S},
   label='r302'
}
reaction{'H + CH2CO ( + M ) <=> CH2CHO ( + M )',
   fr={'pressure dependent',
       k_inf={A=4.86500e+11, n=4.22000e-01, T_a=-1.75500e+03*S},
       k_0={A=1.01200e+42, n=-7.63000e+00, T_a=3.85400e+03*S},
       Troe={a=0.465, T3=201.0, T1=1773.0, T2=5333.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r303'
}
reaction{'O + CH2CHO=> H + CH2 + CO2',
   fr={'Arrhenius', A=1.50000e+14, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r304'
}
reaction{'O2 + CH2CHO=> OH + CO + CH2O',
   fr={'Arrhenius', A=1.81000e+10, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r305'
}
reaction{'O2 + CH2CHO=> OH + 2CHO',
   fr={'Arrhenius', A=2.35000e+10, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r306'
}
reaction{'H + CH2CHO <=> CH3 + CHO',
   fr={'Arrhenius', A=2.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r307'
}
reaction{'H + CH2CHO <=> CH2CO + H2',
   fr={'Arrhenius', A=1.10000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r308'
}
reaction{'OH + CH2CHO <=> H2O + CH2CO',
   fr={'Arrhenius', A=1.20000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r309'
}
reaction{'OH + CH2CHO <=> CHO + CH2OH',
   fr={'Arrhenius', A=3.01000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r310'
}
reaction{'CH3 + C2H5 ( + M ) <=> C3H8 ( + M )',
   fr={'pressure dependent',
       k_inf={A=9.43000e+12, n=0.00000e+00, T_a=0.00000e+00*S},
       k_0={A=2.71000e+74, n=-1.68200e+01, T_a=1.30650e+04*S},
       Troe={a=.1527, T3=291.0, T1=2742.0, T2=7748.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r311'
}
reaction{'O + C3H8 <=> OH + C3H7',
   fr={'Arrhenius', A=1.93000e+05, n=2.68000e+00, T_a=3.71600e+03*S},
   label='r312'
}
reaction{'H + C3H8 <=> C3H7 + H2',
   fr={'Arrhenius', A=1.32000e+06, n=2.54000e+00, T_a=6.75600e+03*S},
   label='r313'
}
reaction{'OH + C3H8 <=> C3H7 + H2O',
   fr={'Arrhenius', A=3.16000e+07, n=1.80000e+00, T_a=9.34000e+02*S},
   label='r314'
}
reaction{'C3H7 + H2O2 <=> HO2 + C3H8',
   fr={'Arrhenius', A=3.78000e+02, n=2.72000e+00, T_a=1.50000e+03*S},
   label='r315'
}
reaction{'CH3 + C3H8 <=> C3H7 + CH4',
   fr={'Arrhenius', A=9.03000e-01, n=3.65000e+00, T_a=7.15400e+03*S},
   label='r316'
}
reaction{'CH3 + C2H4 ( + M ) <=> C3H7 ( + M )',
   fr={'pressure dependent',
       k_inf={A=2.55000e+06, n=1.60000e+00, T_a=5.70000e+03*S},
       k_0={A=3.00000e+63, n=-1.46000e+01, T_a=1.81700e+04*S},
       Troe={a=.1894, T3=277.0, T1=8748.0, T2=7891.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r317'
}
reaction{'O + C3H7 <=> C2H5 + CH2O',
   fr={'Arrhenius', A=9.64000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r318'
}
reaction{'H + C3H7 ( + M ) <=> C3H8 ( + M )',
   fr={'pressure dependent',
       k_inf={A=3.61300e+13, n=0.00000e+00, T_a=0.00000e+00*S},
       k_0={A=4.42000e+61, n=-1.35450e+01, T_a=1.13570e+04*S},
       Troe={a=.315, T3=369.0, T1=3285.0, T2=6667.0},
   },
   efficiencies={H2=2.00, H2O=6.00, CH4=2.00, CO=1.50, CO2=2.00, C2H6=3.00, Ar=0.70},
   label='r319'
}
reaction{'H + C3H7 <=> CH3 + C2H5',
   fr={'Arrhenius', A=4.06000e+06, n=2.19000e+00, T_a=8.90000e+02*S},
   label='r320'
}
reaction{'OH + C3H7 <=> C2H5 + CH2OH',
   fr={'Arrhenius', A=2.41000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r321'
}
reaction{'HO2 + C3H7 <=> O2 + C3H8',
   fr={'Arrhenius', A=2.55000e+10, n=2.55000e-01, T_a=-9.43000e+02*S},
   label='r322'
}
reaction{'HO2 + C3H7=> OH + C2H5 + CH2O',
   fr={'Arrhenius', A=2.41000e+13, n=0.00000e+00, T_a=0.00000e+00*S},
   label='r323'
}
reaction{'CH3 + C3H7 <=> 2C2H5',
   fr={'Arrhenius', A=1.92700e+13, n=-3.20000e-01, T_a=0.00000e+00*S},
   label='r324'
}

