-- Auto-generated by gasfile on: 28-Dec-2010 17:21:16
model = 'composite gas'
equation_of_state = 'Noble-Abel gas'
thermal_behaviour = 'thermally real'
mixing_rule = 'Wilke'
sound_speed = 'equilibrium'
diffusion_coefficients = 'hard sphere'
ignore_mole_fraction = 1.0e-15
T_COLD = 20.0
species = {'O2', 'N2', }

O2 = {}
O2.M = {
  value = 0.031999,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O2.gamma = {
  value = 1.4,
  reference = "diatomic molecule at low temperatures, gamma = 7/5",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
O2.d = {
  value = 3.433e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
O2.T_c = {
  value = 154.58,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical temperature",
  units = "K",
}
O2.p_c = {
  value = 5043000,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical pressure",
  units = "Pa",
}
O2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
O2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
O2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -34255.6342,
      484.700097,
      1.119010961,
      0.00429388924,
      -6.83630052e-07,
      -2.0233727e-09,
      1.039040018e-12,
      -3391.45487,
      18.4969947,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1037939.022,
      2344.830282,
      1.819732036,
      0.001267847582,
      -2.188067988e-07,
      2.053719572e-11,
      -8.19346705e-16,
      -16890.10929,
      17.38716506,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      497529430,
      -286610.6874,
      66.9035225,
      -0.00616995902,
      3.016396027e-07,
      -7.4214166e-12,
      7.27817577e-17,
      2293554.027,
      -553.062161,
    },
  },
  ref = "from CEA2::thermo.inp",
}
N2 = {}
N2.M = {
  value = 0.028013,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
N2.gamma = {
  value = 1.4,
  reference = "diatomic molecule at low temperatures, gamma = 7/5",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
N2.d = {
  value = 3.667e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
N2.T_c = {
  value = 126.2,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical temperature",
  units = "K",
}
N2.p_c = {
  value = 3398000,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical pressure",
  units = "Pa",
}
N2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
N2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
N2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      22103.71497,
      -381.846182,
      6.08273836,
      -0.00853091441,
      1.384646189e-05,
      -9.62579362e-09,
      2.519705809e-12,
      710.846086,
      -10.76003744,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      587712.406,
      -2239.249073,
      6.06694922,
      -0.00061396855,
      1.491806679e-07,
      -1.923105485e-11,
      1.061954386e-15,
      12832.10415,
      -15.86640027,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      831013916,
      -642073.354,
      202.0264635,
      -0.03065092046,
      2.486903333e-06,
      -9.70595411e-11,
      1.437538881e-15,
      4938707.04,
      -1672.09974,
    },
  },
  ref = "from CEA2::thermo.inp",
}
