-- Auto-generated by gasfile on: 28-Dec-2010 17:27:04
model = 'composite gas'
equation_of_state = 'perfect gas'
thermal_behaviour = 'thermally perfect'
mixing_rule = 'Wilke'
sound_speed = 'equilibrium'
diffusion_coefficients = 'hard sphere'
ignore_mole_fraction = 1.0e-15
T_COLD = 20.0
species = {'H2', 'H', 'O', 'O2', 'OH', 'H2O', 'HO2', 'CH2', 'CH2_S', 'CH3', 'CH4', 'CO', 'CO2', 'CHO', 'CH2O', 'CH3O', 'C2H4', 'C2H5', 'C2H6', 'N2', 'Ar', 'He', }

H2 = {}
H2.M = {
  value = 0.00201588,
  reference = "molecular weight from CEA2",
  description = "molecular mass",
  units = "kg/mol",
}
H2.d = {
  value = 3.433e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
H2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 139,
    mu_ref = 1.919e-05,
  },
  model = "Sutherland",
}
H2.thermal_conductivity = {
  parameters = {
    S = 240,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0244,
    T_ref = 273,
  },
  model = "Sutherland",
}
H2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      40783.2321,
      -800.918604,
      8.21470201,
      -0.01269714457,
      1.753605076e-05,
      -1.20286027e-08,
      3.36809349e-12,
      2682.484665,
      -30.43788844,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      560812.801,
      -837.150474,
      2.975364532,
      0.001252249124,
      -3.74071619e-07,
      5.9366252e-11,
      -3.6069941e-15,
      5339.82441,
      -2.202774769,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      496688412,
      -314754.7149,
      79.8412188,
      -0.00841478921,
      4.75324835e-07,
      -1.371873492e-11,
      1.605461756e-16,
      2488433.516,
      -669.572811,
    },
  },
  ref = "from CEA2::thermo.inp",
}
H = {}
H.M = {
  value = 0.00100794,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
H.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
H.viscosity = {
  parameters = {
    {
      A = 0.74226149,
      C = 185541.65,
      B = -401.32865,
      T_high = 5000,
      T_low = 1000,
      D = 0.046741844,
    },
    {
      A = 0.87486623,
      C = 7095504.8,
      B = -2502.2902,
      T_high = 15000,
      T_low = 5000,
      D = -0.93888455,
    },
    ref = "from CEA2::trans.inp which cites Vanderslice et al. (1962)",
  },
  model = "CEA",
}
H.thermal_conductivity = {
  parameters = {
    {
      A = 0.74166119,
      C = 187756.42,
      B = -404.87203,
      T_high = 5000,
      T_low = 1000,
      D = 3.4843121,
    },
    {
      A = 0.87447639,
      C = 7108129.4,
      B = -2508.9452,
      T_high = 15000,
      T_low = 5000,
      D = 2.4970991,
    },
    ref = "from CEA2::trans.inp which cites Vanderslice et al. (1962)",
  },
  model = "CEA",
}
H.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      25473.708,
      -0.446682853,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      60.7877425,
      -0.181935442,
      2.50021182,
      -1.22651286e-07,
      3.73287633e-11,
      -5.68774456e-15,
      3.4102102e-19,
      25474.864,
      -0.448191777,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      217375769,
      -131203.54,
      33.991742,
      -0.00381399968,
      2.43285484e-07,
      -7.69427554e-12,
      9.64410563e-17,
      1067638.09,
      -274.230105,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
O = {}
O.M = {
  value = 0.0159994,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
O.viscosity = {
  parameters = {
    {
      A = 0.77269241,
      C = -58502.098,
      B = 83.842977,
      T_high = 5000,
      T_low = 1000,
      D = 0.85100827,
    },
    {
      A = 0.87669586,
      C = -1088456.6,
      B = 1015.842,
      T_high = 15000,
      T_low = 5000,
      D = -0.18001077,
    },
    ref = "from CEA2::trans.inp which cites Levin et al (1990)",
  },
  model = "CEA",
}
O.thermal_conductivity = {
  parameters = {
    {
      A = 0.77271664,
      C = -58580.966,
      B = 83.9891,
      T_high = 5000,
      T_low = 1000,
      D = 1.51799,
    },
    {
      A = 0.87676666,
      C = -1090669,
      B = 1017.0744,
      T_high = 15000,
      T_low = 5000,
      D = 0.48644232,
    },
    ref = "from CEA2::trans.inp which cites Levin et al (1990)",
  },
  model = "CEA",
}
O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -7953.6113,
      160.7177787,
      1.966226438,
      0.00101367031,
      -1.110415423e-06,
      6.5175075e-10,
      -1.584779251e-13,
      28403.62437,
      8.40424182,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      261902.0262,
      -729.872203,
      3.31717727,
      -0.000428133436,
      1.036104594e-07,
      -9.43830433e-12,
      2.725038297e-16,
      33924.2806,
      -0.667958535,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      177900426.4,
      -108232.8257,
      28.10778365,
      -0.002975232262,
      1.854997534e-07,
      -5.79623154e-12,
      7.191720164e-17,
      889094.263,
      -218.1728151,
    },
  },
  ref = "from CEA2::thermo.inp",
}
O2 = {}
O2.M = {
  value = 0.031999,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
O2.d = {
  value = 3.433e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
O2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 139,
    mu_ref = 1.919e-05,
  },
  model = "Sutherland",
}
O2.thermal_conductivity = {
  parameters = {
    S = 240,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0244,
    T_ref = 273,
  },
  model = "Sutherland",
}
O2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -34255.6342,
      484.700097,
      1.119010961,
      0.00429388924,
      -6.83630052e-07,
      -2.0233727e-09,
      1.039040018e-12,
      -3391.45487,
      18.4969947,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1037939.022,
      2344.830282,
      1.819732036,
      0.001267847582,
      -2.188067988e-07,
      2.053719572e-11,
      -8.19346705e-16,
      -16890.10929,
      17.38716506,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      497529430,
      -286610.6874,
      66.9035225,
      -0.00616995902,
      3.016396027e-07,
      -7.4214166e-12,
      7.27817577e-17,
      2293554.027,
      -553.062161,
    },
  },
  ref = "from CEA2::thermo.inp",
}
OH = {}
OH.M = {
  value = 0.01700734,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
OH.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
OH.viscosity = {
  parameters = {
    {
      A = 0.59711536,
      C = 37606.286,
      B = -461.00678,
      T_high = 5000,
      T_low = 1000,
      D = 2.4041761,
    },
    {
      A = 0.64287721,
      C = -88543.767,
      B = -181.73747,
      T_high = 15000,
      T_low = 5000,
      D = 1.9636057,
    },
    ref = "from CEA2::trans.inp which cites Svehla (1994)",
  },
  model = "CEA",
}
OH.thermal_conductivity = {
  parameters = {
    {
      A = 0.68627561,
      C = 27559.033,
      B = -740.33274,
      T_high = 5000,
      T_low = 1000,
      D = 2.8308741,
    },
    {
      A = -0.47918112,
      C = 7050995.2,
      B = -9376.9908,
      T_high = 15000,
      T_low = 5000,
      D = 14.203688,
    },
    ref = "from CEA2::trans.inp which cites Svehla (1994)",
  },
  model = "CEA",
}
OH.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -1998.85899,
      93.0013616,
      3.050854229,
      0.001529529288,
      -3.157890998e-06,
      3.31544618e-09,
      -1.138762683e-12,
      2991.214235,
      4.67411079,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      1017393.379,
      -2509.957276,
      5.11654786,
      0.000130529993,
      -8.28432226e-08,
      2.006475941e-11,
      -1.556993656e-15,
      20196.40206,
      -11.01282337,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      284723419.3,
      -185953.2612,
      50.082409,
      -0.00514237498,
      2.875536589e-07,
      -8.22881796e-12,
      9.56722902e-17,
      1468393.908,
      -402.355558,
    },
  },
  ref = "from CEA2::thermo.inp",
}
H2O = {}
H2O.M = {
  value = 0.01801528,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
H2O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
H2O.viscosity = {
  parameters = {
    {
      A = 0.50019557,
      C = 88163.892,
      B = -697.12796,
      T_high = 1073.2,
      T_low = 373.2,
      D = 3.0836508,
    },
    {
      A = 0.58988538,
      C = 54263.513,
      B = -537.69814,
      T_high = 5000,
      T_low = 1073.2,
      D = 2.3386375,
    },
    {
      A = 0.64330087,
      C = -377422.83,
      B = -95.668913,
      T_high = 15000,
      T_low = 5000,
      D = 1.812519,
    },
    ref = "from CEA2::trans.inp which cites Sengers and Watson (1986)",
  },
  model = "CEA",
}
H2O.thermal_conductivity = {
  parameters = {
    {
      A = 1.0966389,
      C = 106234.08,
      B = -555.13429,
      T_high = 1073.2,
      T_low = 373.2,
      D = -0.2466455,
    },
    {
      A = 0.39367933,
      C = 612174.58,
      B = -2252.4226,
      T_high = 5000,
      T_low = 1073.2,
      D = 5.8011317,
    },
    {
      A = -0.41858737,
      C = 19179190,
      B = -14096.649,
      T_high = 15000,
      T_low = 5000,
      D = 14.345613,
    },
    ref = "from CEA2::trans.inp which cites Sengers and Watson (1986)",
  },
  model = "CEA",
}
H2O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -39479.6083,
      575.573102,
      0.931782653,
      0.00722271286,
      -7.34255737e-06,
      4.95504349e-09,
      -1.336933246e-12,
      -33039.7431,
      17.24205775,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      1034972.096,
      -2412.698562,
      4.64611078,
      0.002291998307,
      -6.83683048e-07,
      9.42646893e-11,
      -4.82238053e-15,
      -13842.86509,
      -7.97814851,
    },
  },
  ref = "from CEA2::thermo.inp",
}
HO2 = {}
HO2.M = {
  value = 0.03300674,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
HO2.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
HO2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
HO2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
HO2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -75988.8254,
      1329.383918,
      -4.67738824,
      0.02508308202,
      -3.006551588e-05,
      1.895600056e-08,
      -4.82856739e-12,
      -5873.35096,
      51.9360214,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      -1810669.724,
      4963.19203,
      -1.039498992,
      0.00456014853,
      -1.061859447e-06,
      1.144567878e-10,
      -4.76306416e-15,
      -32008.1719,
      40.6685092,
    },
  },
  ref = "from CEA2::thermo.inp",
}
CH2 = {}
CH2.M = {
  value = 0.01402658,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
CH2.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CH2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CH2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      32189.2173,
      -287.7601815,
      4.20358382,
      0.00345540596,
      -6.74619334e-06,
      7.65457164e-09,
      -2.870328419e-12,
      47336.2471,
      -2.143628603,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      2550418.031,
      -7971.62539,
      12.28924487,
      -0.001699122922,
      2.991728605e-07,
      -2.767007492e-11,
      1.05134174e-15,
      96422.1689,
      -60.9473991,
    },
  },
  ref = "from CEA2::thermo.inp",
}
CH2_S = {}
CH2_S.M = {
  value = 0.01402658,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CH2_S.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH2_S.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CH2_S.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CH2_S.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      4.19860411,
      -0.00236661419,
      8.2329622e-06,
      -6.68815981e-09,
      1.94314737e-12,
      50496.8163,
      -0.769118967,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      2.29203842,
      0.00465588637,
      -2.01191947e-06,
      4.17906e-10,
      -3.39716365e-14,
      50925.9997,
      8.62650169,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CH3 = {}
CH3.M = {
  value = 0.01503452,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
CH3.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH3.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CH3.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CH3.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      -28761.8881,
      509.326866,
      0.200214395,
      0.0136360583,
      -1.43398935e-05,
      1.01355673e-08,
      -3.02733194e-12,
      14082.7182,
      20.2277279,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      2760802.66,
      -9336.53117,
      14.8772961,
      -0.00143942977,
      2.44447795e-07,
      -2.22455578e-11,
      8.39506576e-16,
      74818.0948,
      -79.196824,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CH4 = {}
CH4.M = {
  value = 0.01604246,
  reference = "CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
CH4.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH4.viscosity = {
  parameters = {
    {
      A = 0.57643622,
      C = 869.92395,
      B = -93.704079,
      T_high = 1000,
      T_low = 200,
      D = 1.7333347,
    },
    {
      A = 0.66400044,
      C = -7630.7841,
      B = 10.860843,
      T_high = 5000,
      T_low = 1000,
      D = 1.0323984,
    },
    ref = "from CEA2::trans.inp which cites Bousheri et al. (1987) and Svehla (1994)",
  },
  model = "CEA",
}
CH4.thermal_conductivity = {
  parameters = {
    {
      A = 1.0238177,
      C = 32944.309,
      B = -310.92375,
      T_high = 1000,
      T_low = 200,
      D = 0.67787437,
    },
    {
      A = 0.77485028,
      C = -46551.082,
      B = -400.89627,
      T_high = 5000,
      T_low = 1000,
      D = 2.5671481,
    },
    ref = "from CEA2::trans.inp which cites Bousheri et al. (1987) and Svehla (1994)",
  },
  model = "CEA",
}
CH4.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      5.14987613,
      -0.0136709788,
      4.91800599e-05,
      -4.84743026e-08,
      1.66693956e-11,
      -10246.6476,
      -4.64130376,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      0.074851495,
      0.0133909467,
      -5.73285809e-06,
      1.22292535e-09,
      -1.0181523e-13,
      -9468.34459,
      18.437318,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CO = {}
CO.M = {
  value = 0.0280101,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CO.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CO.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CO.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CO.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      3.57953347,
      -0.00061035368,
      1.01681433e-06,
      9.07005884e-10,
      -9.04424499e-13,
      -14344.086,
      3.50840928,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      2.71518561,
      0.00206252743,
      -9.98825771e-07,
      2.30053008e-10,
      -2.03647716e-14,
      -14151.8724,
      7.81868772,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CO2 = {}
CO2.M = {
  value = 0.0440095,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CO2.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CO2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CO2.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CO2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.35677352,
      0.00898459677,
      -7.12356269e-06,
      2.45919022e-09,
      -1.43699548e-13,
      -48371.9697,
      9.90105222,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      3.85746029,
      0.00441437026,
      -2.21481404e-06,
      5.23490188e-10,
      -4.72084164e-14,
      -48759.166,
      2.27163806,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CHO = {}
CHO.M = {
  value = 0.02901804,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CHO.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CHO.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CHO.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CHO.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      4.22118584,
      -0.00324392532,
      1.37799446e-05,
      -1.33144093e-08,
      4.33768865e-12,
      3839.56496,
      3.39437243,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      2.77217438,
      0.00495695526,
      -2.48445613e-06,
      5.89161778e-10,
      -5.33508711e-14,
      4011.91815,
      9.79834492,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CH2O = {}
CH2O.M = {
  value = 0.03002598,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CH2O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH2O.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CH2O.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CH2O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      4.79372315,
      -0.00990833369,
      3.73220008e-05,
      -3.79285261e-08,
      1.31772652e-11,
      -14308.9567,
      0.6028129,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      1.76069008,
      0.00920000082,
      -4.42258813e-06,
      1.00641212e-09,
      -8.8385564e-14,
      -13995.8323,
      13.656323,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
CH3O = {}
CH3O.M = {
  value = 0.03103392,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
CH3O.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
CH3O.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
CH3O.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
CH3O.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 300,
    coeffs = {
      0,
      0,
      2.106204,
      0.007216595,
      5.338472e-06,
      -7.377636e-09,
      2.07561e-12,
      978.6011,
      13.152177,
    },
  },
  {
    T_high = 3000,
    T_low = 1000,
    coeffs = {
      0,
      0,
      3.770799,
      0.007871497,
      -2.656384e-06,
      3.944431e-10,
      -2.112616e-14,
      127.83252,
      2.929575,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
C2H4 = {}
C2H4.M = {
  value = 0.02805316,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
C2H4.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
C2H4.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
C2H4.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
C2H4.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      3.95920148,
      -0.00757052247,
      5.70990292e-05,
      -6.91588753e-08,
      2.69884373e-11,
      5089.77593,
      4.09733096,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      2.03611116,
      0.0146454151,
      -6.71077915e-06,
      1.47222923e-09,
      -1.25706061e-13,
      4939.88614,
      10.3053693,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
C2H5 = {}
C2H5.M = {
  value = 0.0290611,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
C2H5.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
C2H5.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
C2H5.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
C2H5.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      4.30646568,
      -0.00418658892,
      4.97142807e-05,
      -5.99126606e-08,
      2.30509004e-11,
      12841.6265,
      4.70720924,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      1.95465642,
      0.0173972722,
      -7.98206668e-06,
      1.75217689e-09,
      -1.49641576e-13,
      12857.52,
      13.4624343,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
C2H6 = {}
C2H6.M = {
  value = 0.03006904,
  reference = "Periodic table",
  description = "molecular mass",
  units = "kg/mol",
}
C2H6.d = {
  value = 3.617e-10,
  reference = "value for air: Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
C2H6.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
C2H6.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
C2H6.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      4.29142492,
      -0.0055015427,
      5.99438288e-05,
      -7.08466285e-08,
      2.68685771e-11,
      -11522.2055,
      2.66682316,
    },
  },
  {
    T_high = 3500,
    T_low = 1000,
    coeffs = {
      0,
      0,
      1.0718815,
      0.0216852677,
      -1.00256067e-05,
      2.21412001e-09,
      -1.9000289e-13,
      -11426.3932,
      15.1156107,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
N2 = {}
N2.M = {
  value = 0.028013,
  reference = "from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
N2.d = {
  value = 3.667e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard sphere diameter, based on L-J parameters",
  units = "m",
}
N2.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 107,
    mu_ref = 1.663e-05,
  },
  model = "Sutherland",
}
N2.thermal_conductivity = {
  parameters = {
    S = 150,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0242,
    T_ref = 273,
  },
  model = "Sutherland",
}
N2.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      22103.71497,
      -381.846182,
      6.08273836,
      -0.00853091441,
      1.384646189e-05,
      -9.62579362e-09,
      2.519705809e-12,
      710.846086,
      -10.76003744,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      587712.406,
      -2239.249073,
      6.06694922,
      -0.00061396855,
      1.491806679e-07,
      -1.923105485e-11,
      1.061954386e-15,
      12832.10415,
      -15.86640027,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      831013916,
      -642073.354,
      202.0264635,
      -0.03065092046,
      2.486903333e-06,
      -9.70595411e-11,
      1.437538881e-15,
      4938707.04,
      -1672.09974,
    },
  },
  ref = "from CEA2::thermo.inp",
}
Ar = {}
Ar.M = {
  value = 0.039948,
  reference = "molecular weight from CEA2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
Ar.d = {
  value = 3.432e-10,
  reference = "Bird, Stewart and Lightfoot (2001), Appendix E.1",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
Ar.viscosity = {
  parameters = {
    T_ref = 273.1,
    ref = "PJs code: lib/gas_models/source/gas.c",
    S = 144.4,
    mu_ref = 2.125e-05,
  },
  model = "Sutherland",
}
Ar.thermal_conductivity = {
  parameters = {
    {
      A = 0.60968928,
      C = 584.20624,
      B = -70.892249,
      T_high = 1000,
      T_low = 200,
      D = 1.9337152,
    },
    {
      A = 0.69075463,
      C = -25667.413,
      B = 62.676058,
      T_high = 5000,
      T_low = 1000,
      D = 1.2664189,
    },
    {
      A = 0.76269502,
      C = -718995.52,
      B = 623.41752,
      T_high = 15000,
      T_low = 5000,
      D = 0.56927918,
    },
    ref = "from CEA2::trans.inp which cites Bich et al. (1990)",
  },
  model = "CEA",
}
Ar.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      -745.375,
      4.37967491,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      20.10538475,
      -0.0599266107,
      2.500069401,
      -3.99214116e-08,
      1.20527214e-11,
      -1.819015576e-15,
      1.078576636e-19,
      -744.993961,
      4.37918011,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      -995126508,
      645888.726,
      -167.5894697,
      0.02319933363,
      -1.721080911e-06,
      6.53193846e-11,
      -9.740147729e-16,
      -5078300.34,
      1465.298484,
    },
  },
}
He = {}
He.M = {
  value = 0.004003,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864 & 867",
  description = "molecular mass",
  units = "kg/mol",
}
He.d = {
  value = 2.576e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
He.viscosity = {
  parameters = {
    T_ref = 273.1,
    ref = "mu_ref, T_ref: Table 11, Chapman and Cowling (1970)\
S: Table 15, Chapman and Cowling (1970)\
      ",
    S = 72.9,
    mu_ref = 1.865e-05,
  },
  model = "Sutherland",
}
He.thermal_conductivity = {
  parameters = {
    {
      A = 0.75007833,
      C = -2363.66,
      B = 36.577987,
      T_high = 1000,
      T_low = 200,
      D = 2.9766475,
    },
    {
      A = 0.83319259,
      C = -53304.53,
      B = 221.57417,
      T_high = 5000,
      T_low = 1000,
      D = 2.2684592,
    },
    {
      A = 0.85920953,
      C = -1106926.2,
      B = 898.73206,
      T_high = 15000,
      T_low = 5000,
      D = 1.9535742,
    },
    ref = "from CEA2::trans.inp which cites Bich et al. (1990)",
  },
  model = "CEA",
}
He.CEA_coeffs = {
  {
    T_high = 1000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      -745.375,
      0.928723974,
    },
  },
  {
    T_high = 6000,
    T_low = 1000,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      -745.375,
      0.928723974,
    },
  },
  ref = "The Chemkin Thermodynamic Data Base, Kee R.J. et al (1993)",
}
