-- Auto-generated by gasfile on: 12-Jun-2011 12:16:59
model = 'composite gas'
equation_of_state = 'van der Waals gas'
thermal_behaviour = 'thermally real'
mixing_rule = 'Wilke'
sound_speed = 'equilibrium'
ignore_mole_fraction = 1.0e-15
T_COLD = 20.0
species = {'He', }

He = {}
He.M = {
  value = 0.004002602,
  reference = "cea2::thermo.inp",
  description = "molecular mass",
  units = "kg/mol",
}
He.gamma = {
  value = 1.6666666666667,
  reference = "monatomic gas",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
He.d = {
  value = 2.576e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
He.T_c = {
  value = 5.19,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical temperature",
  units = "K",
}
He.p_c = {
  value = 227000,
  reference = "Poling, B.E. et al. (2001). The Properties of Gases and Liquids. Section A, p.A.5",
  description = "critical pressure",
  units = "Pa",
}
He.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
He.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
He.CEA_coeffs = {
  {
    T_high = 6000,
    T_low = 200,
    coeffs = {
      0,
      0,
      2.5,
      0,
      0,
      0,
      0,
      -745.375,
      0.928723974,
    },
  },
  {
    T_high = 20000,
    T_low = 6000,
    coeffs = {
      3396845.42,
      -2194.037652,
      3.080231878,
      -8.06895755e-05,
      6.25278491e-09,
      -2.574990067e-13,
      4.429960218e-18,
      16505.1896,
      -4.04881439,
    },
  },
  ref = "cea2::thermo.inp",
}
