# makefile just to clean directory

clean:
	- rm eilmer3-theory-book.log \
		*.aux \
		eilmer3-theory-book.idx \
		eilmer3-theory-book.ilg \
		eilmer3-theory-book.ind \
		eilmer3-theory-book.bbl \
		eilmer3-theory-book.blg \
		eilmer3-theory-book.toc

all_clean:
	make clean
	- rm eilmer3-theory-book.pdf
