-- Auto-generated by gasfile on: 17-May-2009 20:49:48
-- and edited manually by PJ, 21-Jan-2010
model = 'composite gas'
equation_of_state = 'perfect gas'
thermal_behaviour = 'constant specific heats'
sound_speed = 'equilibrium'
mixing_rule = 'Wilke'
diffusion_coefficients = 'hard sphere'
ignore_mole_fraction = 1.0e-15
species = {'A', 'B', }

A = {}
A.M = {
  value = 8.31451/287.0,
  reference = "Powers and Aslam, artifical gas.",
  description = "molecular mass",
  units = "kg/mol",
}
A.gamma = {
  value = 1.2,
  reference = "Powers and Aslam, artificial gas.",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
A.d = {
  value = 3.617e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "air value: equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
A.e_zero = {
  value = 0,
  description = "reference energy",
  units = "J/kg",
}
A.q = {
  value = 0,
  description = "heat release",
  units = "J/kg",
}
A.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
A.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}

B = {}
B.M = {
  value = 8.31451/287.0,
  reference = "Powers and Aslam, artifical gas.",
  description = "molecular mass",
  units = "kg/mol",
}
B.gamma = {
  value = 1.2,
  reference = "Powers and Aslam, artificial gas.",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
B.d = {
  value = 3.617e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "air value: equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
B.e_zero = {
  value = 0,
  description = "reference energy",
  units = "J/kg",
}
B.q = {
  value = 300000,
  description = "heat release",
  units = "J/kg",
}
B.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
B.thermal_conductivity = {
  parameters = {
    S = 194,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.0241,
    T_ref = 273,
  },
  model = "Sutherland",
}
