language: d

#compiler:
#  - dmd

notifications:
  email: false

env:
  global:
    - secure: "wnthDxOwv7qaVfJQfwYQLFo4DDBgfT4HoLntBsfmYjwmSVzCuXPktCK3vOpimb5twyiVNkt1I/82x8lyYpiczKqPcNZqd8p91mInt5eKIf8Gacqb3a1FwGyk9bwHSZdYpQiblY/wMVb0+WJTuhlVf1NI5xXMWCf1l88+1q6E6jo="

install:
  # dmd
  # dub
  - DMD_VER=2.066.1
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.22
  - DUB=dub-${DUB_VER}-linux-x86_64
  #- sudo apt-get install liblua5.1-0-dev
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz
  # 32-bit deps
  - sudo apt-get install gcc-multilib

script:
  - dub test
  - dub test --arch=x86

after_success:
  - ./push-ddoc.sh

