# makefile for mallinson_cylinder
# Samuel Stennett, Nov 2014

clean:
	- rm -r flow \
		grid \
		heat \
		hist \
		*.list \
                *.log \
                LOGFILE \
                gas-model.lua \
                *.control \
                *.config \
		*.times

all_clean:
	make clean \
	- rm -r plot
