#! /usr/bin/env python
"""
build-cea-lut.py

Build look-up-table for the behaviour of a gas in thermochemical equilibrium.
All of the difficult computation is done by the NASA CEA2 program.
We just collate the results in a form convenient for the gas module of Eilmer3. 

.. Authors: PJ and RJG
.. Version: 06-April-2012: Fresh start, building on cea2_gas module.
"""

import sys, os, time, numpy, math, gzip
sys.path.append(os.path.expandvars("$HOME/e3bin"))
from cfpylib.gasdyn.cea2_gas import make_gas_from_name, Gas, list_gas_names

#-----------------------------------------------------------------------------

def get_e_offset(mygas):
    """
    At a suitably-low value of temperature, compute the energy offset for CEA gas.
    
    :param mygas: cea2 Gas object
    :returns: offset value to be added to CEA internal energy.
    
    It is convenient to have the reference temperature of 0 degrees K
    for internal energy and enthalpy, so that e = C_v * T, approximately.
    This is quite different to the reference temperature of 298 degrees K
    used by CEA, so we'll compute an offset value and shift the CEA value
    of internal energy by this offset in future.
    """ 
    T = 302.0 # Any low temperature will suffice. 
    mygas.set_pT(100.0e3, T)
    # mygas.write_state(sys.stdout)
    return  mygas.C_v * T - mygas.e

def get_e_range(mygas, T_min, T_max, log_rho_values):
    """
    Scan the boundary of the temperature and density to determine 
    the range of internal that can be comfortably computed by CEA.
    """
    e_values = []
    for log_rho in log_rho_values:
        mygas.set_rhoT(math.pow(10.0,log_rho), T_min)
        e_values.append(mygas.e)
    e_min = max(e_values)
    e_values = []
    for log_rho in log_rho_values:
        mygas.set_rhoT(math.pow(10.0,log_rho), T_max)
        e_values.append(mygas.e)
    e_max = min(e_values)
    return e_min, e_max

def build_table(mygas, gasName, T_min=200.0, T_max=20000.0,
                log_rho_min=-6.0, log_rho_max=2.0):
    """
    Compute gas thermo properties for a mesh of internal-energy and density values
    and write an encoded form of the thermo data to a Lua-format file.

    :param mygas: a cea2_gas Gas object
    :param gasname: string name of the gas, used to construct the table file name.
    :param T_min: in degrees K
    :param T_max: in degrees K
    :param log_rho_min: log-base-10 of minimum density in kg/m**3
    :param log_rho_max: log-base-10 of maximum density in kg/m**3

    The file produced is intended for later use by the LUT gas model.
    """
    # Keep density range on a logarithmic scale.
    irsteps = 50
    dlr = (log_rho_max - log_rho_min) / irsteps
    log_rho_values = numpy.linspace(log_rho_min, log_rho_max, irsteps+1)
    #
    # Internal energy range on a linear scale.
    e_offset = get_e_offset(mygas)
    print "e_offset=", e_offset
    e_min, e_max = get_e_range(mygas, T_min, T_max, log_rho_values)
    print "e_min=", e_min, "e_max=", e_max
    iesteps = 400
    de = (e_max - e_min) / iesteps
    e_values = numpy.linspace(e_min, e_max, iesteps+1)
    #
    fname = 'cea-lut-' + gasName + '.lua.gz'
    print "Writing out look-up table: %s" % fname
    fp = gzip.open(fname, 'wb')
    fp.write("-- Auto-generated by build-cea-lut.py on: %s\n" % time.asctime())
    fp.write("model = 'look-up table'\n")
    fp.write("iesteps = %d\n" % iesteps)
    fp.write("irsteps = %d\n" % irsteps)
    # It is nice to have e = Cv * T in the table.
    fp.write("emin = %g\n" % (e_min+e_offset))
    fp.write("de = %g\n" % de)
    fp.write("lrmin = %g\n" % log_rho_min)
    fp.write("dlr = %g\n" % dlr)
    # Now, write the table data.
    fp.write("data = {\n")
    for e in e_values:
        print '*',
        sys.stdout.flush()
        fp.write("{\n")
        for log_rho in log_rho_values:
            rho = math.pow(10.0, log_rho)
            mygas.set_rhoe(rho, e)
            Cv_hat = (e + e_offset) / mygas.T
            R_hat = mygas.p / (rho * mygas.T)
            gamma_hat = mygas.a * mygas.a / (R_hat * mygas.T)
            fp.write("{%g, %g, %g, %g, %g, %g},\n" %
                     (Cv_hat, mygas.C_v, R_hat, gamma_hat, mygas.mu, mygas.k))
        fp.write("},\n")
    fp.write("}\n\n")
    fp.close()
    print
    return

#-----------------------------------------------------------------------------
def list_gases(option, opt, value, parser):
    print "Available gases are:"
    for name in list_gas_names():
        print "   %s" % name
    print ""
    sys.exit()
    

if __name__ == '__main__':
    print "Begin build-cea-lut.py..."
    from optparse import OptionParser, OptionGroup
    usage = "Usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("-g", "--gas", action="store", type="string", dest="gasName",
                      help="name of built-in gas mixture")
    parser.add_option("-l", "--list-gases", action="callback", callback=list_gases,
                      help="list available gas names and exit")
    parser.add_option("-c", "--custom", action="store_true", dest="custom", default=False,
                      help="build a custom gas model from reactants")
    parser.add_option("-b", "--bounds", action="store", type="string", dest="bounds",
                      default="200.0,20000.0,-6.0,2.0",
                      help="bounds of the table in form \"T_min,T_max,log_rho_min,log_rho_max\"")
    group = OptionGroup(parser, "Custom gas options")
    group.add_option("-r", "--reactants", action="store", type="string", dest="reactants",
                     help="reactant fractions in dictionary form")
    group.add_option("-o", "--only-list", action="store", type="string", dest="onlyList",
                     help="limit species to this list")
    group.add_option("-m", "--moles", action="store_const", dest="inputUnits", default="moles",
                     help="reactant fractions as mole fractions [default]")
    group.add_option("-f", "--massf", action="store_const", dest="inputUnits",
                     help="reactant fractions as mass fractions")
    group.add_option("-n", "--no-ions", action="store_false", dest="withIons", default=False,
                     help="excluding ions [default]")
    group.add_option("-i", "--with-ions", action="store_true", dest="withIons",
                     help="including ions")
    parser.add_option_group(group)
    (options, args) = parser.parse_args()
    if options.gasName == None and not options.custom:
        parser.print_help()
        print ""
        print "Example 1: build-cea-lut.py --gas=air5species"
        print "Example 2: build-cea-lut.py --custom --reactants=\"N2:0.79,O2:0.21\" --only-list=\"N2,O2,NO,O,N\""
        sys.exit()
    T_min, T_max, log_rho_min, log_rho_max = [float(item) for item in options.bounds.split(',')]
    print "    log_rho_min=", log_rho_min, "log_rho_max=", log_rho_max
    print "    T_min=", T_min, "T_max=", T_max
    if options.custom:
        print "Building table for custom gas:"
        print "    reactants=", options.reactants
        print "    inputUnits=", options.inputUnits
        print "    onlyList=", options.onlyList
        print "    withIons=", options.withIons
        if options.reactants == None:
            parser.print_help()
            print "To build a custom gas model, you need to specify reactant fractions"
            print "in dictionary form.  For example: --reactants=\"N2:0.79,O2:0.21\""
            sys.exit()
        reactants = {}
        for species in options.reactants.split(','):
            name, fraction = species.split(':')
            reactants[name] = float(fraction)
        onlyList = []
        if options.onlyList != None:
            for name in options.onlyList.split(','):
                onlyList.append(name)
        mygas = Gas(reactants, onlyList, options.inputUnits, with_ions=options.withIons)
        gasName = "custom"
    else:
        print "Building table for gas name: ", options.gasName
        mygas = make_gas_from_name(options.gasName)
        gasName = options.gasName
    build_table(mygas, gasName, T_min, T_max, log_rho_min, log_rho_max)
    print "Done."
