-- Auto-generated by gasfile on: 20-Sep-2010 20:46:50
model = 'composite gas'
equation_of_state = 'perfect gas'
thermal_behaviour = 'constant specific heats'
mixing_rule = 'Wilke'
sound_speed = 'equilibrium'
ignore_mole_fraction = 1.0e-15
species = {'air', }

air = {}
air.M = {
  value = 0.028964,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864 & 867",
  description = "molecular mass",
  units = "kg/mol",
}
air.gamma = {
  value = 1.4,
  reference = "Anderson Jr. (1989), p. 441",
  description = "(ideal) ratio of specific heats at room temperature",
  units = "non-dimensional",
}
air.d = {
  value = 3.617e-10,
  reference = "Bird, Stewart and Lightfoot (2001), p. 864",
  description = "equivalent hard-sphere diameter, sigma from L-J parameters",
  units = "m",
}
air.e_zero = {
  value = 0,
  description = "reference energy",
  units = "J/kg",
}
air.q = {
  value = 0,
  description = "heat release",
  units = "J/kg",
}
air.viscosity = {
  parameters = {
    T_ref = 273,
    ref = "Table 1-2, White (2006)",
    S = 111,
    mu_ref = 1.716e-05,
  },
  model = "Sutherland",
}
air.thermal_conductivity = {
  parameters = {
    S = 111,
    ref = "Table 1-3, White (2006)",
    k_ref = 0.024283154347991,
    T_ref = 273,
  },
  model = "Sutherland",
}
