#!/bin/sh
# plot-exit-profiles.sh
#
# Plots the flow profiles at the exit of the nozzle from the nozzle-exit.data
# file that has been generated by NENZFr.
#
# Wilson Chan, 31 Aug 2012
#- --------------------------------------------------------------------------

gnuplot<<EOF
set term postscript eps color enhanced size 12cm,9cm
set output "profile-Mach.eps"
set xlabel "Radial distance from axis, m"
set ylabel "Mach number"
set xrange [0:0.135]
set yrange [0:8]
plot "nozzle-exit.data" using (\$2):(\$21) with lines lt 1 lc 1
EOF

gnuplot<<EOF
set term postscript eps color enhanced size 12cm,9cm
set output "profile-Pitot.eps"
set xlabel "Radial distance from axis, m"
set ylabel "Pitot pressure, kPa"
set xrange [0:0.135]
set yrange [0:100]
plot "nozzle-exit.data" using (\$2):((\$22)/1000) with lines lt 1 lc 1
EOF

gnuplot<<EOF
set term postscript eps color enhanced size 12cm,9cm
set output "profile-flow-divergence.eps"
set xlabel "Radial distance from axis, m"
set ylabel "Flow divergence, degrees"
set xrange [0:0.135]
set yrange [-5:5]
plot "nozzle-exit.data" using (\$2):(atan((\$7)/(\$6)*180/pi)) with lines lt 1 lc 1
EOF

epstopdf profile-Mach.eps
epstopdf profile-Pitot.eps
epstopdf profile-flow-divergence.eps
rm *eps
